# Generated by Django 5.1.15 on 2026-08-12 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ess', '0002_employee_organization_employment_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('accessory', 'Accessory'), ('software', 'Software'), ('other', 'Other')], max_length=16)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='submitted', max_length=12)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-requested_on',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('accessory', 'Accessory'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=16)),
                ('serial', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=12)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('assigned', 'Assigned'), ('repair', 'In repair'), ('retired', 'Retired')], default='in_stock', max_length=12)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('assigned_on', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('organization', 'serial')},
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('vendor', models.CharField(blank=True, max_length=128)),
                ('seats_total', models.PositiveIntegerField(default=0)),
                ('seats_used', models.PositiveIntegerField(default=0)),
                ('cost_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
