# Generated by Django 5.1.15 on 2026-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='payroll_day_of_month',
            field=models.PositiveSmallIntegerField(default=25, help_text='Used for monthly / semi-monthly schedules'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='payroll_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-weekly'), ('weekly', 'Weekly'), ('semi_monthly', 'Semi-monthly')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='payroll_weekday',
            field=models.CharField(default='friday', help_text='Used for weekly / bi-weekly schedules (monday-friday)', max_length=10),
        ),
    ]
