# Generated by Django 5.1.15 on 2026-08-29 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        ('ess', '0002_employee_organization_employment_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('preboarding', 'Preboarding'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('offboarding', 'Offboarding'), ('separated', 'Separated')], default='preboarding', max_length=16)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('hr_verified_at', models.DateTimeField(blank=True, null=True)),
                ('exit_type', models.CharField(blank=True, choices=[('resignation', 'Resignation'), ('termination', 'Termination')], max_length=16)),
                ('exit_reason', models.TextField(blank=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('access_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle', to='ess.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_lifecycles', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LifecycleChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('owner', models.CharField(default='HR', max_length=64)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='lifecycle.lifecyclerecord')),
            ],
            options={
                'ordering': ('phase', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='LifecycleAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('allocate', 'Allocate'), ('return', 'Return')], max_length=16)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset')),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_actions', to='lifecycle.lifecyclerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifecycleApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=32)),
                ('approved', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lifecycle.lifecyclerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
