# Generated by Django 5.1.15 on 2026-07-25 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ess', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=128)),
                ('task', models.CharField(max_length=128)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('billable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='ess.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('wfh', 'Work from home'), ('half-day', 'Half-day')], default='present', max_length=16)),
                ('shift', models.CharField(blank=True, max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='ess.employee')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
