import { useEffect, useState } from "react";
import { PageHeader, SectionCard, StatusBadge, Button, Input } from "@/components";
import { apiGet, apiPost, apiPatch, camelizeKeys, unwrapList, snakeizeKeys } from "@/lib/api";

type Task = { id: string; title: string; description?: string; status: string; priority: string; dueDate?: string | null; assignee?: string | null };

export default function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Task | null>(null);
  const [comment, setComment] = useState("");
  const [assignee, setAssignee] = useState("");
  const [activity, setActivity] = useState<Array<{ id: string; action: string; createdAt: string }>>([]);
  const openTask = async (task: Task) => { setSelected(task); try { const raw = await apiGet<any>(`/api/tasks/${task.id}/activity/`); setActivity(unwrapList(raw, (row) => camelizeKeys(row))); } catch { setActivity([]); } };
  const load = async () => { setLoading(true); setError(null); try { const raw = await apiGet<any>("/api/tasks/", { params: search ? { search } : {} }); setTasks(unwrapList<Task>(raw, (r) => camelizeKeys<Task>(r))); } catch { setError("Couldn’t load tasks."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [search]);
  const updateStatus = async (task: Task, status: string) => { await apiPatch(`/api/tasks/${task.id}/`, snakeizeKeys({ status })); await load(); };
  return <main className="space-y-6"><PageHeader title="Tasks" description="Track work, ownership, and delivery." actions={<Button onClick={() => void apiPost("/api/tasks/", { title: "New task", priority: "medium", status: "todo" }).then(load)}>Create task</Button>} /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search tasks" />{error ? <SectionCard title="Tasks unavailable"><div className="flex items-center justify-between"><span>{error}</span><Button variant="outline" onClick={() => void load()}>Retry</Button></div></SectionCard> : null}<SectionCard title={`${tasks.length} tasks`}>{loading ? <p>Loading…</p> : tasks.length ? <div className="divide-y">{tasks.map((task) => <div key={task.id} className="flex items-center justify-between gap-4 py-4"><div><button className="font-medium text-left hover:underline" onClick={() => void openTask(task)}>{task.title}</button><p className="text-sm text-muted-foreground">{task.dueDate ? `Due ${task.dueDate}` : "No due date"}</p></div><div className="flex items-center gap-3"><StatusBadge tone={task.priority === "urgent" ? "destructive" : task.status === "completed" ? "success" : "info"}>{task.status.replace("_", " ")}</StatusBadge><Button size="sm" variant="outline" onClick={() => void updateStatus(task, task.status === "completed" ? "todo" : "completed")}>{task.status === "completed" ? "Reopen" : "Complete"}</Button></div></div>)}</div> : <p className="text-sm text-muted-foreground">No tasks found.</p>}</SectionCard>{selected ? <SectionCard title={selected.title}><div className="space-y-4"><p className="text-sm text-muted-foreground">{selected.description || "No description provided."}</p><div className="flex gap-2"><Input aria-label="Assignee user ID" value={assignee} onChange={(event) => setAssignee(event.target.value)} placeholder="Assignee user ID" /><Button variant="outline" disabled={!assignee.trim()} onClick={() => void apiPatch(`/api/tasks/${selected.id}/`, snakeizeKeys({ assignee })).then(() => { toast.success("Task assigned."); return load(); }).catch(() => toast.error("Couldn’t assign this task."))}>Assign</Button></div>{activity.length ? <div className="space-y-1 text-xs text-muted-foreground">{activity.map((item) => <p key={item.id}>{item.action} · {item.createdAt}</p>)}</div> : null}<div className="flex gap-2"><Input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add a comment" /><Button disabled={!comment.trim()} onClick={() => void apiPost(`/api/tasks/${selected.id}/comments/`, { body: comment }).then(() => { setComment(""); toast.success("Comment added."); })}>Comment</Button></div><Button variant="outline" onClick={() => setSelected(null)}>Close</Button></div></SectionCard> : null}</main>;
}
