# Generated by Django 5.1.15 on 2026-07-25 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('leave', 'Leave'), ('payroll', 'Payroll'), ('system', 'System'), ('team', 'Team'), ('learning', 'Learning'), ('helpdesk', 'Helpdesk')], default='system', max_length=16)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
