# Generated by Django 6.0.7 on 2026-08-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='employment',
            name='band',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employment',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employment',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='employment',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='performance_rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=3),
        ),
        migrations.AddField(
            model_name='employment',
            name='potential',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8),
        ),
        migrations.AddField(
            model_name='employment',
            name='salary_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('notice', 'Notice period'), ('probation', 'Probation'), ('exited', 'Exited')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='employment',
            name='team',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
