# Generated by Django 5.1.15 on 2026-08-12 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ess', '0002_employee_organization_employment_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('health', 'Health'), ('insurance', 'Insurance'), ('wellness', 'Wellness'), ('retirement', 'Retirement'), ('perk', 'Perk')], max_length=16)),
                ('provider', models.CharField(max_length=128)),
                ('coverage', models.CharField(blank=True, max_length=128)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('renewal_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('office', 'Office'), ('medical', 'Medical'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('approver', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='receipts/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='benefits.expenseclaim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('booked', 'Booked'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('approver', models.CharField(blank=True, max_length=128)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-from_date',),
            },
        ),
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired')], default='active', max_length=12)),
                ('claims', models.PositiveIntegerField(default=0)),
                ('usage', models.PositiveIntegerField(default=0)),
                ('enrolled_on', models.DateField()),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='benefits.benefit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-enrolled_on',),
                'unique_together': {('employee', 'benefit')},
            },
        ),
    ]
