# Generated by Django 5.1.15 on 2026-08-09 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['organization', 'user', '-updated_at'], name='ai_aiconver_organiz_f61103_idx'),
        ),
    ]
