# Generated by Django 5.1.15 on 2026-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiconversation_options_alter_aimessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='provider',
            field=models.CharField(default='openai', max_length=40),
        ),
    ]
