# Generated by Django 5.1.15 on 2026-08-12 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ess', '0002_employee_organization_employment_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('issuer', models.CharField(max_length=128)),
                ('credential_id', models.CharField(blank=True, max_length=96)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring', 'Expiring'), ('expired', 'Expired')], default='valid', max_length=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-issued_on',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('provider', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cover', models.CharField(blank=True, max_length=255)),
                ('mandatory', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=64)),
                ('format', models.CharField(choices=[('instructor', 'Instructor led'), ('self_paced', 'Self paced'), ('blended', 'Blended')], default='blended', max_length=16)),
                ('duration_hrs', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=12)),
                ('mandatory', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('employee', 'course')},
            },
        ),
        migrations.CreateModel(
            name='SkillMatrixEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.CharField(max_length=96)),
                ('category', models.CharField(max_length=64)),
                ('beginner', models.PositiveIntegerField(default=0)),
                ('intermediate', models.PositiveIntegerField(default=0)),
                ('advanced', models.PositiveIntegerField(default=0)),
                ('expert', models.PositiveIntegerField(default=0)),
                ('gap', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('skill',),
                'unique_together': {('organization', 'skill')},
            },
        ),
    ]
