# Generated by Django 5.1.15 on 2026-07-25 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ess', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=16)),
                ('period', models.CharField(blank=True, max_length=32)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('processing', 'Processing'), ('released', 'Released')], default='processing', max_length=16)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='ess.employee')),
            ],
            options={
                'ordering': ('-month',),
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=16)),
                ('label', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
