import {
  LayoutDashboard,
  User,
  FileText,
  Clock,
  CalendarDays,
  Wallet,
  Heart,
  Laptop,
  GraduationCap,
  TrendingUp,
  Building2,
  LifeBuoy,
  Send,
  Bell,
  Settings,
  Users,
  Briefcase,
  MapPin,
  ShieldAlert,
  UsersRound,
  Files,
  IdCard,
  Award,
  BookOpen,
  History as HistoryIcon,
  CalendarCheck,
  CalendarClock,
  ListChecks,
  Timer,
  PlaneTakeoff,
  ScrollText,
  BadgeDollarSign,
  Receipt,
  PiggyBank,
  Shield,
  Landmark,
  Boxes,
  ClipboardList,
  Route as RouteIcon,
  Target,
  BarChart3,
  Sparkles,
  Network,
  Megaphone,
  CalendarRange,
  CheckSquare,
  MessageSquare,
  Ticket,
  Book,
  Plane,
  ReceiptText,
  KeyRound,
  Lock,
  Fingerprint,
  Monitor,
  EyeOff,
  SlidersHorizontal,
  UserPlus,
  UserMinus,
  UserCheck,
  Users2,
  Contact,
  Workflow,
  ClipboardCheck,
  MessageCircle,
  Layers,
  Building,
  ShieldCheck,
  FileSearch,
  Handshake,
  Trophy,
  PieChart,
  LineChart as LineChartIcon,
  Repeat,
  ArrowRightIcon,
  Wand2,
  Inbox,
  BadgeCheck,
  Scale,
  Gavel,
  Star,
  Flag,
  BellRing,
  BarChart,
  Fingerprint as FingerprintIcon,
  Gift,
} from "lucide-react";
import { PERMISSIONS } from "./permissions";
import type { NavSection } from "@/types";

export const NAVIGATION: NavSection[] = [
  {
    label: "Workspace",
    items: [
      { label: "Dashboard", path: "/", icon: LayoutDashboard, permission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Notifications", path: "/notifications", icon: Bell, permission: PERMISSIONS.NOTIFICATIONS_VIEW },
      { label: "Messages", path: "/messages", icon: MessageSquare, permission: PERMISSIONS.NOTIFICATIONS_VIEW },
      { label: "Tasks", path: "/tasks", icon: CheckSquare, permission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Calendar", path: "/calendar", icon: CalendarRange, permission: PERMISSIONS.DASHBOARD_VIEW },
    ],
  },
  {
    label: "Me",
    items: [
      {
        label: "Profile",
        path: "/profile/personal",
        icon: User,
        permission: PERMISSIONS.PROFILE_VIEW,
      },
      // {
      //   label: "Profile",
      //   icon: User,
      //   permission: PERMISSIONS.PROFILE_VIEW,
      //   children: [
      //     { label: "Personal Information", path: "/profile/personal", icon: User },
      //     { label: "Contact Information", path: "/profile/contact", icon: MapPin },
      //     { label: "Employment Information", path: "/profile/employment", icon: Briefcase },
      //     { label: "Organization Information", path: "/profile/organization", icon: Building2 },
      //     { label: "Emergency Contacts", path: "/profile/emergency", icon: ShieldAlert },
      //     { label: "Family Information", path: "/profile/family", icon: UsersRound },
      //   ],
      // },
      {
        label: "Documents",
        path: "/documents",
        icon: FileText,
        permission: PERMISSIONS.DOCUMENTS_VIEW,
      },
      // {
      //   label: "Documents",
      //   icon: FileText,
      //   permission: PERMISSIONS.DOCUMENTS_VIEW,
      //   children: [
      //     { label: "All Documents", path: "/documents", icon: Files },
      //     { label: "Identity Documents", path: "/documents/identity", icon: IdCard },
      //     { label: "Employment Documents", path: "/documents/employment", icon: Briefcase },
      //     { label: "Certificates", path: "/documents/certificates", icon: Award },
      //     { label: "Education", path: "/documents/education", icon: BookOpen },
      //     { label: "Experience", path: "/documents/experience", icon: HistoryIcon },
      //   ],
      // },
    ],
  },
  {
    label: "Time & Attendance",
    items: [
      {
        label: "Attendance",
        icon: Clock,
        permission: PERMISSIONS.ATTENDANCE_VIEW,
        children: [
          { label: "Today", path: "/attendance/today", icon: Timer },
          // { label: "Clock In", path: "/attendance/clock-in", icon: CalendarCheck },
          // { label: "Clock Out", path: "/attendance/clock-out", icon: CalendarClock },
          // { label: "Calendar", path: "/attendance/calendar", icon: CalendarDays },
          { label: "History", path: "/attendance/history", icon: HistoryIcon },
          { label: "Timesheets", path: "/attendance/timesheets", icon: ListChecks },
          // { label: "Work Schedule", path: "/attendance/schedule", icon: CalendarClock },
        ],
      },
      {
        label: "Leave",
        icon: PlaneTakeoff,
        permission: PERMISSIONS.LEAVE_VIEW,
        children: [
          { label: "Dashboard", path: "/leave", icon: LayoutDashboard },
          { label: "Balance", path: "/leave/balance", icon: PiggyBank },
          { label: "Apply Leave", path: "/leave/apply", icon: Send },
          { label: "History", path: "/leave/history", icon: HistoryIcon },
          // { label: "Approval Status", path: "/leave/approvals", icon: ScrollText },
          { label: "Holiday Calendar", path: "/leave/holidays", icon: CalendarDays },
        ],
      },
    ],
  },
  {
    label: "Finance",
    items: [
      {
        label: "Payroll",
        icon: Wallet,
        permission: PERMISSIONS.PAYROLL_VIEW,
        children: [
          { label: "Dashboard", path: "/payroll", icon: LayoutDashboard },
          { label: "Salary Summary", path: "/payroll/salary", icon: BadgeDollarSign },
          { label: "Payslips", path: "/payroll/payslips", icon: Receipt },
          { label: "Tax Documents", path: "/payroll/tax", icon: FileText },
          { label: "Bank Details", path: "/payroll/bank", icon: Landmark },
        ],
      },
      {
        label: "Benefits",
        icon: Heart,
        permission: PERMISSIONS.BENEFITS_VIEW,
        children: [
          { label: "Overview", path: "/benefits", icon: Heart },
          { label: "Insurance", path: "/benefits/insurance", icon: Shield },
          { label: "Reimbursements", path: "/benefits/reimbursements", icon: Receipt },
          { label: "Expense Claims", path: "/benefits/expenses", icon: ReceiptText },
        ],
      },
    ],
  },
  {
    label: "Workplace",
    items: [
      {
        label: "Assets",
        icon: Laptop,
        permission: PERMISSIONS.ASSETS_VIEW,
        children: [
          { label: "Assigned Devices", path: "/assets/devices", icon: Monitor },
          { label: "Accessories", path: "/assets/accessories", icon: Boxes },
          { label: "Requests", path: "/assets/requests", icon: ClipboardList },
          { label: "History", path: "/assets/history", icon: HistoryIcon },
        ],
      },
      {
        label: "Learning",
        icon: GraduationCap,
        permission: PERMISSIONS.LEARNING_VIEW,
        children: [
          { label: "Courses", path: "/learning/courses", icon: BookOpen },
          { label: "Certifications", path: "/learning/certifications", icon: Award },
          { label: "Progress", path: "/learning/progress", icon: TrendingUp },
        ],
      },
      {
        label: "Career",
        icon: TrendingUp,
        permission: PERMISSIONS.CAREER_VIEW,
        children: [
          { label: "Career Path", path: "/career/path", icon: RouteIcon },
          { label: "Goals", path: "/career/goals", icon: Target },
          { label: "Performance Reviews", path: "/career/reviews", icon: BarChart3 },
          { label: "Skills", path: "/career/skills", icon: Sparkles },
          { label: "Training", path: "/career/training", icon: GraduationCap },
        ],
      },
    ],
  },
  {
    label: "Organization",
    items: [
      {
        label: "Organization",
        icon: Building2,
        permission: PERMISSIONS.ORG_VIEW,
        children: [
          { label: "Company Directory", path: "/org/directory", icon: Users },
          { label: "My Team", path: "/org/team", icon: UsersRound },
          { label: "Reporting Manager", path: "/org/manager", icon: User },
          { label: "Organization Chart", path: "/org/chart", icon: Network },
          { label: "Announcements", path: "/org/announcements", icon: Megaphone },
          { label: "Events", path: "/org/events", icon: CalendarRange },
        ],
      },
    ],
  },
  {
    label: "Support",
    items: [
      {
        label: "Help Desk",
        icon: LifeBuoy,
        permission: PERMISSIONS.HELPDESK_VIEW,
        children: [
          { label: "Support Tickets", path: "/helpdesk/tickets", icon: Ticket },
          { label: "Knowledge Base", path: "/helpdesk/knowledge", icon: Book },
        ],
      },
      {
        label: "Requests",
        icon: Send,
        permission: PERMISSIONS.REQUESTS_VIEW,
        children: [
          { label: "Travel Requests", path: "/requests/travel", icon: Plane },
          { label: "Expense Requests", path: "/requests/expense", icon: ReceiptText },
        ],
      },
    ],
  },

  // ─────────────── HR ADMINISTRATION (Phase 2) ───────────────
  {
    label: "HR · Overview",
    items: [
      { label: "HR Dashboard", path: "/hr", icon: LayoutDashboard, permission: PERMISSIONS.HR_DASHBOARD_VIEW },
      { label: "Approval Center", path: "/hr/approvals", icon: Inbox, permission: PERMISSIONS.HR_APPROVALS_VIEW },
      { label: "Activity Feed", path: "/hr/activity", icon: BellRing, permission: PERMISSIONS.HR_DASHBOARD_VIEW },
    ],
  },
  {
    label: "HR · People",
    items: [
      {
        label: "Employee Management",
        icon: Users2,
        permission: PERMISSIONS.HR_EMPLOYEES_VIEW,
        children: [
          { label: "Employee Directory", path: "/hr/employees", icon: Contact },
          { label: "Employee Profile", path: "/hr/employees/profile", icon: User },
          { label: "Employee Lifecycle", path: "/hr/employees/lifecycle", icon: Repeat },
        ],
      },
      {
        label: "Organization Structure",
        icon: Network,
        permission: PERMISSIONS.HR_ORG_STRUCTURE_VIEW,
        children: [
          { label: "Departments", path: "/hr/org/departments", icon: Building },
          { label: "Teams", path: "/hr/org/teams", icon: UsersRound },
          { label: "Designations", path: "/hr/org/designations", icon: BadgeCheck },
          { label: "Locations", path: "/hr/org/locations", icon: MapPin },
          { label: "Organization Chart", path: "/hr/org/chart", icon: Network },
        ],
      },
    ],
  },
  {
    label: "HR · Talent",
    items: [
      {
        label: "Recruitment",
        icon: UserPlus,
        permission: PERMISSIONS.HR_RECRUITMENT_VIEW,
        children: [
          { label: "Job Requisitions", path: "/hr/recruitment/requisitions", icon: ClipboardList },
          { label: "Job Openings", path: "/hr/recruitment/openings", icon: Briefcase },
          { label: "Career Portal", path: "/hr/recruitment/career-portal", icon: Building },
          { label: "Candidate Pipeline", path: "/hr/recruitment/pipeline", icon: Workflow },
          { label: "Candidate Profile", path: "/hr/recruitment/candidate", icon: User },
          { label: "Interview Scheduling", path: "/hr/recruitment/interviews", icon: CalendarClock },
          { label: "Interview Feedback", path: "/hr/recruitment/feedback", icon: MessageCircle },
          { label: "Offer Management", path: "/hr/recruitment/offers", icon: Handshake },
          { label: "Hiring Analytics", path: "/hr/recruitment/analytics", icon: BarChart3 },
          { label: "Talent Pool", path: "/hr/recruitment/talent-pool", icon: Users },
        ],
      },
      {
        label: "Onboarding",
        icon: UserCheck,
        permission: PERMISSIONS.HR_ONBOARDING_VIEW,
        children: [
          { label: "New Hire Dashboard", path: "/hr/onboarding", icon: LayoutDashboard },
          { label: "Document Collection", path: "/hr/onboarding/documents", icon: FileText },
          { label: "Task Checklist", path: "/hr/onboarding/tasks", icon: ClipboardCheck },
          { label: "Equipment Assignment", path: "/hr/onboarding/equipment", icon: Laptop },
          { label: "Orientation Schedule", path: "/hr/onboarding/orientation", icon: CalendarDays },
          { label: "Buddy Assignment", path: "/hr/onboarding/buddy", icon: UsersRound },
        ],
      },
      {
        label: "Offboarding",
        icon: UserMinus,
        permission: PERMISSIONS.HR_OFFBOARDING_VIEW,
        children: [
          { label: "Resignation Requests", path: "/hr/offboarding/resignations", icon: ScrollText },
          { label: "Exit Checklist", path: "/hr/offboarding/checklist", icon: ClipboardCheck },
          { label: "Exit Interviews", path: "/hr/offboarding/interviews", icon: MessageCircle },
          { label: "Asset Recovery", path: "/hr/offboarding/assets", icon: Laptop },
          { label: "Clearances", path: "/hr/offboarding/clearances", icon: ShieldCheck },
          { label: "Final Settlement", path: "/hr/offboarding/settlement", icon: Wallet },
        ],
      },
    ],
  },
  {
    label: "HR · Growth",
    items: [
      {
        label: "Performance",
        icon: Trophy,
        permission: PERMISSIONS.HR_PERFORMANCE_VIEW,
        children: [
          { label: "Performance Cycles", path: "/hr/performance/cycles", icon: Repeat },
          { label: "Review Templates", path: "/hr/performance/templates", icon: FileText },
          { label: "Employee Reviews", path: "/hr/performance/employee-reviews", icon: ClipboardCheck },
          { label: "Manager Reviews", path: "/hr/performance/manager-reviews", icon: ClipboardList },
          { label: "360 Feedback", path: "/hr/performance/360", icon: MessageCircle },
          { label: "Goals & OKRs", path: "/hr/performance/goals", icon: Target },
          { label: "Competencies", path: "/hr/performance/competencies", icon: Layers },
          { label: "Performance Analytics", path: "/hr/performance/analytics", icon: BarChart3 },
        ],
      },
      {
        label: "Learning & Development",
        icon: GraduationCap,
        permission: PERMISSIONS.HR_LND_VIEW,
        children: [
          { label: "Learning Dashboard", path: "/hr/lnd", icon: LayoutDashboard },
          { label: "Training Programs", path: "/hr/lnd/programs", icon: BookOpen },
          { label: "Course Management", path: "/hr/lnd/courses", icon: Book },
          { label: "Learning Assignments", path: "/hr/lnd/assignments", icon: ClipboardList },
          { label: "Certifications", path: "/hr/lnd/certifications", icon: Award },
          { label: "Skill Matrix", path: "/hr/lnd/skills", icon: Layers },
          { label: "Career Development", path: "/hr/lnd/career", icon: RouteIcon },
        ],
      },
      {
        label: "Compensation",
        icon: BadgeDollarSign,
        permission: PERMISSIONS.HR_COMPENSATION_VIEW,
        children: [
          { label: "Salary Bands", path: "/hr/compensation/bands", icon: Layers },
          { label: "Grade Structure", path: "/hr/compensation/grades", icon: BadgeCheck },
          { label: "Promotion Recommendations", path: "/hr/compensation/promotions", icon: TrendingUp },
          { label: "Increment Planning", path: "/hr/compensation/increments", icon: LineChartIcon },
          { label: "Compensation History", path: "/hr/compensation/history", icon: HistoryIcon },
        ],
      },
      {
        label: "Workforce Planning",
        icon: PieChart,
        permission: PERMISSIONS.HR_WORKFORCE_VIEW,
        children: [
          { label: "Headcount Dashboard", path: "/hr/workforce", icon: LayoutDashboard },
          { label: "Organization Chart", path: "/hr/workforce/org-chart", icon: Network },
          { label: "Succession Planning", path: "/hr/workforce/succession", icon: RouteIcon },
          { label: "Talent Reviews", path: "/hr/workforce/talent-reviews", icon: Star },
          { label: "Attrition Dashboard", path: "/hr/workforce/attrition", icon: TrendingUp },
        ],
      },
    ],
  },
  {
    label: "HR · Operations",
    items: [
      {
        label: "Leave Administration",
        icon: PlaneTakeoff,
        permission: PERMISSIONS.HR_LEAVE_ADMIN_VIEW,
        children: [
          { label: "Leave Policies", path: "/hr/leave-admin/policies", icon: ScrollText },
          { label: "Leave Types", path: "/hr/leave-admin/types", icon: Layers },
          { label: "Approval Workflows", path: "/hr/leave-admin/workflows", icon: Workflow },
          { label: "Leave Reports", path: "/hr/leave-admin/reports", icon: BarChart3 },
          { label: "Holiday Management", path: "/hr/leave-admin/holidays", icon: CalendarDays },
        ],
      },
      {
        label: "Attendance Administration",
        icon: Clock,
        permission: PERMISSIONS.HR_ATTENDANCE_ADMIN_VIEW,
        children: [
          { label: "Attendance Dashboard", path: "/hr/attendance-admin", icon: LayoutDashboard },
          { label: "Attendance Corrections", path: "/hr/attendance-admin/corrections", icon: Wand2 },
          { label: "Shift Management", path: "/hr/attendance-admin/shifts", icon: CalendarClock },
          { label: "Roster Planning", path: "/hr/attendance-admin/roster", icon: CalendarRange },
          { label: "Late Arrival Rules", path: "/hr/attendance-admin/late-rules", icon: Timer },
          { label: "Overtime Rules", path: "/hr/attendance-admin/overtime", icon: Clock },
          { label: "Attendance Reports", path: "/hr/attendance-admin/reports", icon: BarChart3 },
        ],
      },
      {
        label: "Document Management",
        icon: Files,
        permission: PERMISSIONS.HR_DOCUMENTS_ADMIN_VIEW,
        children: [
          { label: "Employee Documents", path: "/hr/documents/employees", icon: FileText },
          { label: "Policy Documents", path: "/hr/documents/policies", icon: ScrollText },
          { label: "HR Templates", path: "/hr/documents/templates", icon: FileText },
          { label: "Compliance Documents", path: "/hr/documents/compliance", icon: ShieldCheck },
          { label: "Document Expiry", path: "/hr/documents/expiry", icon: Timer },
        ],
      },
      {
        label: "Compliance",
        icon: ShieldCheck,
        permission: PERMISSIONS.HR_COMPLIANCE_VIEW,
        children: [
          { label: "Policy Management", path: "/hr/compliance/policies", icon: ScrollText },
          { label: "Compliance Dashboard", path: "/hr/compliance", icon: LayoutDashboard },
          { label: "Background Verification", path: "/hr/compliance/bgv", icon: FileSearch },
          { label: "Visa Tracking", path: "/hr/compliance/visa", icon: Plane },
          { label: "Contract Management", path: "/hr/compliance/contracts", icon: FileText },
          { label: "Audit Trail", path: "/hr/compliance/audit", icon: HistoryIcon },
        ],
      },
    ],
  },
  {
    label: "HR · Culture",
    items: [
      {
        label: "Employee Relations",
        icon: Scale,
        permission: PERMISSIONS.HR_RELATIONS_VIEW,
        children: [
          { label: "Grievances", path: "/hr/relations/grievances", icon: Flag },
          { label: "Cases", path: "/hr/relations/cases", icon: FileText },
          { label: "Disciplinary Actions", path: "/hr/relations/disciplinary", icon: Gavel },
          { label: "Warnings", path: "/hr/relations/warnings", icon: ShieldAlert },
          { label: "Recognition", path: "/hr/relations/recognition", icon: Trophy },
          { label: "Surveys", path: "/hr/relations/surveys", icon: ClipboardList },
        ],
      },
      {
        label: "Engagement",
        icon: Heart,
        permission: PERMISSIONS.HR_ENGAGEMENT_VIEW,
        children: [
          { label: "Announcements", path: "/hr/engagement/announcements", icon: Megaphone },
          { label: "Pulse Surveys", path: "/hr/engagement/pulse", icon: BarChart },
          { label: "Recognition Feed", path: "/hr/engagement/feed", icon: Sparkles },
          { label: "Awards", path: "/hr/engagement/awards", icon: Gift },
        ],
      },
    ],
  },
  {
    label: "HR · Analytics",
    items: [
      {
        label: "HR Analytics",
        icon: BarChart3,
        permission: PERMISSIONS.HR_ANALYTICS_VIEW,
        children: [
          { label: "Headcount Analytics", path: "/hr/analytics/headcount", icon: Users },
          { label: "Hiring Analytics", path: "/hr/analytics/hiring", icon: UserPlus },
          { label: "Attrition Analytics", path: "/hr/analytics/attrition", icon: TrendingUp },
          { label: "Performance Analytics", path: "/hr/analytics/performance", icon: Trophy },
          { label: "Diversity Analytics", path: "/hr/analytics/diversity", icon: PieChart },
          { label: "Leave Analytics", path: "/hr/analytics/leave", icon: PlaneTakeoff },
          { label: "Attendance Analytics", path: "/hr/analytics/attendance", icon: Clock },
          { label: "Department Analytics", path: "/hr/analytics/departments", icon: Building },
          { label: "Custom Reports", path: "/hr/analytics/reports", icon: FileText },
        ],
      },
    ],
  },

  // ─────────────── SYSTEM ADMINISTRATION & IT (Phase 3) ───────────────
  {
    label: "Admin · Overview",
    items: [
      { label: "Admin Dashboard", path: "/admin", icon: LayoutDashboard, permission: PERMISSIONS.ADMIN_DASHBOARD_VIEW },
      { label: "AI Admin Assistant", path: "/admin/ai", icon: Sparkles, permission: PERMISSIONS.ADMIN_AI_VIEW },
    ],
  },
  {
    label: "Admin · Organization",
    items: [
      {
        label: "Organization",
        icon: Building2,
        permission: PERMISSIONS.ADMIN_ORG_VIEW,
        children: [
          { label: "Organization Profile", path: "/admin/org/profile", icon: Building },
          { label: "Organization Settings", path: "/admin/org/settings", icon: Settings },
          { label: "Business Units", path: "/admin/org/business-units", icon: Layers },
          { label: "Departments", path: "/admin/org/departments", icon: Building },
          { label: "Branches", path: "/admin/org/branches", icon: Network },
          { label: "Legal Entities", path: "/admin/org/legal-entities", icon: Scale },
          { label: "Cost Centers", path: "/admin/org/cost-centers", icon: Wallet },
          { label: "Office Locations", path: "/admin/org/locations", icon: MapPin },
          { label: "Company Branding", path: "/admin/org/branding", icon: Sparkles },
          { label: "Business Hours", path: "/admin/org/hours", icon: Clock },
          { label: "Working Days", path: "/admin/org/working-days", icon: CalendarDays },
          { label: "Holiday Calendars", path: "/admin/org/holidays", icon: CalendarRange },
          { label: "Organization Policies", path: "/admin/org/policies", icon: ScrollText },
        ],
      },
    ],
  },
  {
    label: "Admin · Access",
    items: [
      {
        label: "User Management",
        icon: Users,
        permission: PERMISSIONS.ADMIN_USERS_VIEW,
        children: [
          { label: "User Directory", path: "/admin/users", icon: Contact },
          { label: "Create User", path: "/admin/users/create", icon: UserPlus },
          { label: "Invite User", path: "/admin/users/invite", icon: Send },
          { label: "Bulk Import", path: "/admin/users/import", icon: Files },
          { label: "Bulk Export", path: "/admin/users/export", icon: Files },
          { label: "Deactivated Users", path: "/admin/users/deactivated", icon: UserMinus },
          { label: "Suspended Users", path: "/admin/users/suspended", icon: ShieldAlert },
          { label: "Employee Mapping", path: "/admin/users/mapping", icon: Repeat },
          { label: "External Users", path: "/admin/users/external", icon: UsersRound },
          { label: "Contractors", path: "/admin/users/contractors", icon: Briefcase },
          { label: "Service Accounts", path: "/admin/users/service-accounts", icon: KeyRound },
        ],
      },
      {
        label: "Roles & Permissions",
        icon: ShieldCheck,
        permission: PERMISSIONS.ADMIN_ROLES_VIEW,
        children: [
          { label: "Roles", path: "/admin/roles", icon: ShieldCheck },
          { label: "Permission Library", path: "/admin/roles/permissions", icon: Book },
          { label: "Permission Groups", path: "/admin/roles/permission-groups", icon: Layers },
          { label: "Custom Roles", path: "/admin/roles/custom", icon: BadgeCheck },
          { label: "Role Assignment", path: "/admin/roles/assignment", icon: UserCheck },
          { label: "Bulk Role Assignment", path: "/admin/roles/bulk-assignment", icon: Users2 },
          { label: "Feature Permissions", path: "/admin/roles/feature", icon: SlidersHorizontal },
          { label: "Page Permissions", path: "/admin/roles/page", icon: FileText },
          { label: "Module Permissions", path: "/admin/roles/module", icon: Boxes },
          { label: "Field-Level Permissions", path: "/admin/roles/field", icon: ListChecks },
          { label: "Data Access Policies", path: "/admin/roles/data-access", icon: Lock },
          { label: "Approval Permissions", path: "/admin/roles/approvals", icon: ClipboardCheck },
          { label: "Role Hierarchy", path: "/admin/roles/hierarchy", icon: Network },
          { label: "Permission Simulator", path: "/admin/roles/simulator", icon: Wand2 },
        ],
      },
      {
        label: "Identity & Access",
        icon: Fingerprint,
        permission: PERMISSIONS.ADMIN_IAM_VIEW,
        children: [
          { label: "Authentication Settings", path: "/admin/iam/auth", icon: Lock },
          { label: "Single Sign-On (SSO)", path: "/admin/iam/sso", icon: KeyRound },
          { label: "OAuth Providers", path: "/admin/iam/oauth", icon: ShieldCheck },
          { label: "SAML Configuration", path: "/admin/iam/saml", icon: Shield },
          { label: "Multi-Factor Auth", path: "/admin/iam/mfa", icon: Fingerprint },
          { label: "Password Policies", path: "/admin/iam/passwords", icon: KeyRound },
          { label: "Session Management", path: "/admin/iam/sessions", icon: Monitor },
          { label: "Device Trust", path: "/admin/iam/device-trust", icon: BadgeCheck },
          { label: "IP Restrictions", path: "/admin/iam/ip-restrictions", icon: Shield },
          { label: "Conditional Access", path: "/admin/iam/conditional-access", icon: SlidersHorizontal },
          { label: "API Tokens", path: "/admin/iam/api-tokens", icon: KeyRound },
          { label: "Personal Access Tokens", path: "/admin/iam/pat", icon: KeyRound },
          { label: "Service Tokens", path: "/admin/iam/service-tokens", icon: KeyRound },
          { label: "Connected Accounts", path: "/admin/iam/connected-accounts", icon: Handshake },
        ],
      },
    ],
  },
  {
    label: "Admin · IT",
    items: [
      {
        label: "Application Management",
        icon: Boxes,
        permission: PERMISSIONS.ADMIN_APPS_VIEW,
        children: [
          { label: "Installed Applications", path: "/admin/apps", icon: Boxes },
          { label: "Marketplace", path: "/admin/apps/marketplace", icon: Star },
          { label: "Internal Applications", path: "/admin/apps/internal", icon: Building },
          { label: "Third-party Integrations", path: "/admin/apps/third-party", icon: Handshake },
          { label: "Application Access", path: "/admin/apps/access", icon: Lock },
          { label: "License Assignment", path: "/admin/apps/licenses", icon: BadgeCheck },
          { label: "Application Categories", path: "/admin/apps/categories", icon: Layers },
          { label: "Provisioning", path: "/admin/apps/provisioning", icon: UserPlus },
          { label: "Deprovisioning", path: "/admin/apps/deprovisioning", icon: UserMinus },
          { label: "Application Analytics", path: "/admin/apps/analytics", icon: BarChart3 },
        ],
      },
      {
        label: "Device Management",
        icon: Monitor,
        permission: PERMISSIONS.ADMIN_DEVICES_VIEW,
        children: [
          { label: "Device Inventory", path: "/admin/devices", icon: Monitor },
          { label: "Laptops", path: "/admin/devices/laptops", icon: Laptop },
          { label: "Desktops", path: "/admin/devices/desktops", icon: Monitor },
          { label: "Mobile Devices", path: "/admin/devices/mobile", icon: Monitor },
          { label: "Tablets", path: "/admin/devices/tablets", icon: Monitor },
          { label: "Device Assignment", path: "/admin/devices/assignment", icon: UserCheck },
          { label: "Device Recovery", path: "/admin/devices/recovery", icon: Repeat },
          { label: "Device Lifecycle", path: "/admin/devices/lifecycle", icon: Repeat },
          { label: "Device Health", path: "/admin/devices/health", icon: ShieldCheck },
          { label: "Operating Systems", path: "/admin/devices/os", icon: Layers },
          { label: "Installed Software", path: "/admin/devices/software", icon: Boxes },
          { label: "Compliance Status", path: "/admin/devices/compliance", icon: ShieldCheck },
          { label: "Lost Devices", path: "/admin/devices/lost", icon: ShieldAlert },
          { label: "Retired Devices", path: "/admin/devices/retired", icon: HistoryIcon },
        ],
      },
      {
        label: "Software Management",
        icon: Boxes,
        permission: PERMISSIONS.ADMIN_SOFTWARE_VIEW,
        children: [
          { label: "Software Inventory", path: "/admin/software", icon: Boxes },
          { label: "License Management", path: "/admin/software/licenses", icon: BadgeCheck },
          { label: "Software Requests", path: "/admin/software/requests", icon: ClipboardList },
          { label: "Version Tracking", path: "/admin/software/versions", icon: Layers },
          { label: "Patch Management", path: "/admin/software/patches", icon: Wand2 },
          { label: "Approval Workflow", path: "/admin/software/approvals", icon: Workflow },
          { label: "Installed Applications", path: "/admin/software/installed", icon: Boxes },
          { label: "Compliance", path: "/admin/software/compliance", icon: ShieldCheck },
        ],
      },
      {
        label: "Asset Management",
        icon: Laptop,
        permission: PERMISSIONS.ADMIN_ASSETS_VIEW,
        children: [
          { label: "Assets Dashboard", path: "/admin/assets", icon: LayoutDashboard },
          { label: "Asset Categories", path: "/admin/assets/categories", icon: Layers },
          { label: "Asset Assignment", path: "/admin/assets/assignment", icon: UserCheck },
          { label: "Asset Requests", path: "/admin/assets/requests", icon: ClipboardList },
          { label: "Asset Recovery", path: "/admin/assets/recovery", icon: Repeat },
          { label: "Asset Maintenance", path: "/admin/assets/maintenance", icon: Wand2 },
          { label: "Warranty Tracking", path: "/admin/assets/warranty", icon: ShieldCheck },
          { label: "Vendor Information", path: "/admin/assets/vendors", icon: Building },
          { label: "Purchase History", path: "/admin/assets/purchases", icon: HistoryIcon },
          { label: "Depreciation Summary", path: "/admin/assets/depreciation", icon: LineChartIcon },
          { label: "Asset Reports", path: "/admin/assets/reports", icon: BarChart3 },
        ],
      },
    ],
  },
  {
    label: "Admin · Operations",
    items: [
      {
        label: "Workflow Management",
        icon: Workflow,
        permission: PERMISSIONS.ADMIN_WORKFLOWS_VIEW,
        children: [
          { label: "Approval Workflows", path: "/admin/workflows", icon: Workflow },
          { label: "Workflow Builder", path: "/admin/workflows/builder", icon: Wand2 },
          { label: "Automation Rules", path: "/admin/workflows/automation", icon: Sparkles },
          { label: "Triggers", path: "/admin/workflows/triggers", icon: Flag },
          { label: "Notifications", path: "/admin/workflows/notifications", icon: Bell },
          { label: "Escalations", path: "/admin/workflows/escalations", icon: TrendingUp },
          { label: "Approval Matrix", path: "/admin/workflows/matrix", icon: Layers },
          { label: "Workflow Templates", path: "/admin/workflows/templates", icon: FileText },
        ],
      },
      {
        label: "Security Center",
        icon: Shield,
        permission: PERMISSIONS.ADMIN_SECURITY_VIEW,
        children: [
          { label: "Security Dashboard", path: "/admin/security", icon: LayoutDashboard },
          { label: "Audit Logs", path: "/admin/security/audit", icon: HistoryIcon },
          { label: "Login History", path: "/admin/security/logins", icon: FingerprintIcon },
          { label: "Failed Logins", path: "/admin/security/failed-logins", icon: ShieldAlert },
          { label: "Permission Changes", path: "/admin/security/permission-changes", icon: ShieldCheck },
          { label: "Administrative Actions", path: "/admin/security/admin-actions", icon: Gavel },
          { label: "Security Events", path: "/admin/security/events", icon: BellRing },
          { label: "Risk Alerts", path: "/admin/security/risks", icon: ShieldAlert },
          { label: "Policy Violations", path: "/admin/security/violations", icon: Flag },
          { label: "Compliance Reports", path: "/admin/security/compliance", icon: FileSearch },
          { label: "Threat Overview", path: "/admin/security/threats", icon: ShieldAlert },
        ],
      },
    ],
  },
  {
    label: "Admin · Platform",
    items: [
      {
        label: "System Configuration",
        icon: SlidersHorizontal,
        permission: PERMISSIONS.ADMIN_CONFIG_VIEW,
        children: [
          { label: "General Settings", path: "/admin/config", icon: Settings },
          { label: "Localization", path: "/admin/config/localization", icon: MapPin },
          { label: "Currencies", path: "/admin/config/currencies", icon: BadgeDollarSign },
          { label: "Languages", path: "/admin/config/languages", icon: Book },
          { label: "Time Zones", path: "/admin/config/timezones", icon: Clock },
          { label: "Date Formats", path: "/admin/config/date-formats", icon: CalendarDays },
          { label: "Email Configuration", path: "/admin/config/email", icon: Send },
          { label: "Notification Templates", path: "/admin/config/notification-templates", icon: Bell },
          { label: "Feature Flags", path: "/admin/config/feature-flags", icon: Flag },
          { label: "Maintenance Mode", path: "/admin/config/maintenance", icon: Wand2 },
          { label: "Branding", path: "/admin/config/branding", icon: Sparkles },
          { label: "Environment Settings", path: "/admin/config/environment", icon: Layers },
        ],
      },
      {
        label: "Integrations",
        icon: Network,
        permission: PERMISSIONS.ADMIN_INTEGRATIONS_VIEW,
        children: [
          { label: "Google Workspace", path: "/admin/integrations/google", icon: Handshake },
          { label: "Microsoft 365", path: "/admin/integrations/microsoft", icon: Handshake },
          { label: "Slack", path: "/admin/integrations/slack", icon: MessageSquare },
          { label: "Microsoft Teams", path: "/admin/integrations/teams", icon: MessageSquare },
          { label: "Zoom", path: "/admin/integrations/zoom", icon: MessageCircle },
          { label: "Jira", path: "/admin/integrations/jira", icon: ClipboardList },
          { label: "GitHub", path: "/admin/integrations/github", icon: Boxes },
          { label: "GitLab", path: "/admin/integrations/gitlab", icon: Boxes },
          { label: "Okta", path: "/admin/integrations/okta", icon: ShieldCheck },
          { label: "Azure AD", path: "/admin/integrations/azure-ad", icon: ShieldCheck },
          { label: "AWS", path: "/admin/integrations/aws", icon: Boxes },
          { label: "Webhook Manager", path: "/admin/integrations/webhooks", icon: Workflow },
          { label: "API Keys", path: "/admin/integrations/api-keys", icon: KeyRound },
          { label: "Integration Logs", path: "/admin/integrations/logs", icon: HistoryIcon },
        ],
      },
      {
        label: "Notifications",
        icon: Bell,
        permission: PERMISSIONS.ADMIN_NOTIFICATIONS_VIEW,
        children: [
          { label: "Notification Center", path: "/admin/notifications", icon: Bell },
          { label: "Email Templates", path: "/admin/notifications/email", icon: Send },
          { label: "SMS Templates", path: "/admin/notifications/sms", icon: MessageSquare },
          { label: "Push Notifications", path: "/admin/notifications/push", icon: BellRing },
          { label: "System Alerts", path: "/admin/notifications/alerts", icon: ShieldAlert },
          { label: "Broadcast Messages", path: "/admin/notifications/broadcast", icon: Megaphone },
          { label: "Announcements", path: "/admin/notifications/announcements", icon: Megaphone },
        ],
      },
      {
        label: "Reports",
        icon: BarChart3,
        permission: PERMISSIONS.ADMIN_REPORTS_VIEW,
        children: [
          { label: "User Reports", path: "/admin/reports/users", icon: Users },
          { label: "Access Reports", path: "/admin/reports/access", icon: Lock },
          { label: "Security Reports", path: "/admin/reports/security", icon: Shield },
          { label: "Asset Reports", path: "/admin/reports/assets", icon: Laptop },
          { label: "Application Reports", path: "/admin/reports/applications", icon: Boxes },
          { label: "Audit Reports", path: "/admin/reports/audit", icon: HistoryIcon },
          { label: "License Reports", path: "/admin/reports/licenses", icon: BadgeCheck },
          { label: "Compliance Reports", path: "/admin/reports/compliance", icon: FileSearch },
          { label: "Custom Reports", path: "/admin/reports/custom", icon: FileText },
        ],
      },
    ],
  },

  // ─────────────── PAYROLL, COMPENSATION, BENEFITS, TIME (Phase 4) ───────────────
  {
    label: "Pay · Overview",
    items: [
      { label: "Payroll Dashboard", path: "/payroll", icon: LayoutDashboard, permission: PERMISSIONS.PAY_DASHBOARD_VIEW },
      { label: "AI Payroll Assistant", path: "/pay/ai", icon: Sparkles, permission: PERMISSIONS.PAY_AI_VIEW },
    ],
  },
  {
    label: "Pay · Payroll",
    items: [
      {
        label: "Payroll Management",
        icon: Wallet,
        permission: PERMISSIONS.PAY_RUNS_VIEW,
        children: [
          { label: "Payroll Runs", path: "/pay/runs", icon: Repeat },
          { label: "Payroll Calendar", path: "/pay/runs/calendar", icon: CalendarRange },
          { label: "Payroll Processing", path: "/pay/runs/processing", icon: Workflow },
          { label: "Approval Workflow", path: "/pay/runs/approvals", icon: ClipboardCheck },
          { label: "Payroll History", path: "/pay/runs/history", icon: HistoryIcon },
          { label: "Payroll Reports", path: "/pay/runs/reports", icon: BarChart3 },
          { label: "Payroll Comparison", path: "/pay/runs/comparison", icon: LineChartIcon },
          { label: "Payroll Analytics", path: "/pay/runs/analytics", icon: BarChart },
          { label: "Payroll Audit Trail", path: "/pay/runs/audit", icon: FileSearch },
          { label: "Off-cycle Payroll", path: "/pay/runs/off-cycle", icon: Wand2 },
          { label: "Payroll Locking", path: "/pay/runs/locking", icon: Lock },
          { label: "Payroll Recalculation", path: "/pay/runs/recalculate", icon: Repeat },
        ],
      },
      {
        label: "Compensation",
        icon: BadgeDollarSign,
        permission: PERMISSIONS.PAY_COMPENSATION_VIEW,
        children: [
          { label: "Salary Structures", path: "/pay/comp/structures", icon: Layers },
          { label: "Compensation Plans", path: "/pay/comp/plans", icon: ScrollText },
          { label: "Salary Components", path: "/pay/comp/components", icon: Boxes },
          { label: "Allowances", path: "/pay/comp/allowances", icon: Gift },
          { label: "Deductions", path: "/pay/comp/deductions", icon: ReceiptText },
          { label: "Bonuses", path: "/pay/comp/bonuses", icon: Trophy },
          { label: "Variable Pay", path: "/pay/comp/variable", icon: TrendingUp },
          { label: "Commissions", path: "/pay/comp/commissions", icon: Handshake },
          { label: "Overtime Payments", path: "/pay/comp/overtime", icon: Clock },
          { label: "Shift Allowances", path: "/pay/comp/shift-allowances", icon: CalendarClock },
          { label: "Annual Compensation", path: "/pay/comp/annual", icon: BarChart3 },
          { label: "Salary Revision History", path: "/pay/comp/revisions", icon: HistoryIcon },
          { label: "Promotion Adjustments", path: "/pay/comp/promotions", icon: TrendingUp },
          { label: "Increment Recommendations", path: "/pay/comp/increments", icon: LineChartIcon },
          { label: "Compensation Analytics", path: "/pay/comp/analytics", icon: BarChart3 },
        ],
      },
      {
        label: "Payslips",
        icon: Receipt,
        permission: PERMISSIONS.PAY_PAYSLIPS_VIEW,
        children: [
          { label: "Current Payslip", path: "/pay/payslips/current", icon: Receipt },
          { label: "Historical Payslips", path: "/pay/payslips/history", icon: HistoryIcon },
          { label: "Download PDF", path: "/pay/payslips/download", icon: FileText },
          { label: "Email Payslip", path: "/pay/payslips/email", icon: Send },
          { label: "Tax Breakdown", path: "/pay/payslips/tax-breakdown", icon: ReceiptText },
          { label: "Salary Breakdown", path: "/pay/payslips/salary-breakdown", icon: PieChart },
          { label: "Allowances", path: "/pay/payslips/allowances", icon: Gift },
          { label: "Deductions", path: "/pay/payslips/deductions", icon: ReceiptText },
          { label: "Employer Contributions", path: "/pay/payslips/employer", icon: Handshake },
          { label: "Yearly Summary", path: "/pay/payslips/yearly", icon: BarChart },
        ],
      },
      {
        label: "Tax Management",
        icon: ReceiptText,
        permission: PERMISSIONS.PAY_TAX_VIEW,
        children: [
          { label: "Income Tax", path: "/pay/tax/income", icon: ReceiptText },
          { label: "Tax Declarations", path: "/pay/tax/declarations", icon: ScrollText },
          { label: "Tax Documents", path: "/pay/tax/documents", icon: FileText },
          { label: "Investment Proofs", path: "/pay/tax/proofs", icon: FileSearch },
          { label: "Tax Calculations", path: "/pay/tax/calculations", icon: Wand2 },
          { label: "Professional Tax", path: "/pay/tax/professional", icon: Briefcase },
          { label: "Provident Fund", path: "/pay/tax/pf", icon: PiggyBank },
          { label: "ESI", path: "/pay/tax/esi", icon: Shield },
          { label: "Social Security", path: "/pay/tax/social-security", icon: Shield },
          { label: "Country Tax Rules", path: "/pay/tax/rules", icon: Scale },
          { label: "Tax Reports", path: "/pay/tax/reports", icon: BarChart3 },
        ],
      },
    ],
  },
  {
    label: "Pay · Benefits & Claims",
    items: [
      {
        label: "Benefits Management",
        icon: Heart,
        permission: PERMISSIONS.PAY_BENEFITS_VIEW,
        children: [
          { label: "Benefits Dashboard", path: "/pay/benefits", icon: LayoutDashboard },
          { label: "Insurance Plans", path: "/pay/benefits/insurance", icon: Shield },
          { label: "Medical Benefits", path: "/pay/benefits/medical", icon: Heart },
          { label: "Dental Benefits", path: "/pay/benefits/dental", icon: Heart },
          { label: "Vision Benefits", path: "/pay/benefits/vision", icon: Heart },
          { label: "Life Insurance", path: "/pay/benefits/life", icon: Shield },
          { label: "Retirement Plans", path: "/pay/benefits/retirement", icon: PiggyBank },
          { label: "Provident Fund", path: "/pay/benefits/pf", icon: PiggyBank },
          { label: "Gratuity", path: "/pay/benefits/gratuity", icon: Gift },
          { label: "Wellness Programs", path: "/pay/benefits/wellness", icon: Sparkles },
          { label: "Flexible Benefits", path: "/pay/benefits/flex", icon: SlidersHorizontal },
          { label: "Benefit Enrollment", path: "/pay/benefits/enrollment", icon: ClipboardCheck },
          { label: "Benefit Claims", path: "/pay/benefits/claims", icon: Receipt },
          { label: "Usage Analytics", path: "/pay/benefits/analytics", icon: BarChart3 },
        ],
      },
      {
        label: "Reimbursements",
        icon: ReceiptText,
        permission: PERMISSIONS.PAY_REIMBURSEMENTS_VIEW,
        children: [
          { label: "Expense Dashboard", path: "/pay/reimburse", icon: LayoutDashboard },
          { label: "Claim Submission", path: "/pay/reimburse/submit", icon: Send },
          { label: "Expense Categories", path: "/pay/reimburse/categories", icon: Layers },
          { label: "Travel Expenses", path: "/pay/reimburse/travel", icon: Plane },
          { label: "Food Expenses", path: "/pay/reimburse/food", icon: Gift },
          { label: "Medical Claims", path: "/pay/reimburse/medical", icon: Heart },
          { label: "Office Expenses", path: "/pay/reimburse/office", icon: Building },
          { label: "Approval Workflow", path: "/pay/reimburse/approvals", icon: Workflow },
          { label: "Claim History", path: "/pay/reimburse/history", icon: HistoryIcon },
          { label: "Pending Claims", path: "/pay/reimburse/pending", icon: Inbox },
          { label: "Approved Claims", path: "/pay/reimburse/approved", icon: BadgeCheck },
          { label: "Rejected Claims", path: "/pay/reimburse/rejected", icon: ShieldAlert },
          { label: "Analytics", path: "/pay/reimburse/analytics", icon: BarChart3 },
        ],
      },
      {
        label: "Loans & Advances",
        icon: Landmark,
        permission: PERMISSIONS.PAY_LOANS_VIEW,
        children: [
          { label: "Employee Loans", path: "/pay/loans", icon: Landmark },
          { label: "Salary Advances", path: "/pay/loans/advances", icon: BadgeDollarSign },
          { label: "Loan Requests", path: "/pay/loans/requests", icon: ClipboardList },
          { label: "Approval Workflow", path: "/pay/loans/approvals", icon: Workflow },
          { label: "Repayment Schedule", path: "/pay/loans/repayment", icon: CalendarClock },
          { label: "Outstanding Balance", path: "/pay/loans/balance", icon: Wallet },
          { label: "Loan History", path: "/pay/loans/history", icon: HistoryIcon },
        ],
      },
    ],
  },
  {
    label: "Pay · Time",
    items: [
      {
        label: "Leave Administration",
        icon: PlaneTakeoff,
        permission: PERMISSIONS.PAY_LEAVE_ADMIN_VIEW,
        children: [
          { label: "Leave Policies", path: "/pay/leave/policies", icon: ScrollText },
          { label: "Leave Types", path: "/pay/leave/types", icon: Layers },
          { label: "Accrual Rules", path: "/pay/leave/accrual", icon: Repeat },
          { label: "Carry Forward", path: "/pay/leave/carry-forward", icon: ArrowRightIcon },
          { label: "Leave Encashment", path: "/pay/leave/encashment", icon: BadgeDollarSign },
          { label: "Leave Calendar", path: "/pay/leave/calendar", icon: CalendarRange },
          { label: "Holiday Calendar", path: "/pay/leave/holidays", icon: CalendarDays },
          { label: "Regional Holidays", path: "/pay/leave/regional", icon: MapPin },
          { label: "Approval Workflows", path: "/pay/leave/workflows", icon: Workflow },
          { label: "Leave Reports", path: "/pay/leave/reports", icon: BarChart3 },
          { label: "Leave Analytics", path: "/pay/leave/analytics", icon: BarChart },
          { label: "Balance Configuration", path: "/pay/leave/balance-config", icon: SlidersHorizontal },
        ],
      },
      {
        label: "Attendance Management",
        icon: Clock,
        permission: PERMISSIONS.PAY_ATTENDANCE_VIEW,
        children: [
          { label: "Attendance Dashboard", path: "/pay/attendance", icon: LayoutDashboard },
          { label: "Clock In", path: "/pay/attendance/clock-in", icon: CalendarCheck },
          { label: "Clock Out", path: "/pay/attendance/clock-out", icon: CalendarClock },
          { label: "Attendance Calendar", path: "/pay/attendance/calendar", icon: CalendarRange },
          { label: "Corrections", path: "/pay/attendance/corrections", icon: Wand2 },
          { label: "Attendance Reports", path: "/pay/attendance/reports", icon: BarChart3 },
          { label: "Policies", path: "/pay/attendance/policies", icon: ScrollText },
          { label: "Exceptions", path: "/pay/attendance/exceptions", icon: ShieldAlert },
          { label: "Late Arrival Rules", path: "/pay/attendance/late", icon: Timer },
          { label: "Early Departure Rules", path: "/pay/attendance/early", icon: Timer },
          { label: "Missing Punches", path: "/pay/attendance/missing", icon: Flag },
          { label: "Analytics", path: "/pay/attendance/analytics", icon: BarChart },
        ],
      },
      {
        label: "Shift Management",
        icon: CalendarClock,
        permission: PERMISSIONS.PAY_SHIFTS_VIEW,
        children: [
          { label: "Shift Planning", path: "/pay/shifts/planning", icon: CalendarRange },
          { label: "Shift Templates", path: "/pay/shifts/templates", icon: FileText },
          { label: "Shift Assignment", path: "/pay/shifts/assignment", icon: UserCheck },
          { label: "Rotational Shifts", path: "/pay/shifts/rotational", icon: Repeat },
          { label: "Night Shifts", path: "/pay/shifts/night", icon: Clock },
          { label: "Weekend Shifts", path: "/pay/shifts/weekend", icon: CalendarDays },
          { label: "Shift Calendar", path: "/pay/shifts/calendar", icon: CalendarRange },
          { label: "Shift Swaps", path: "/pay/shifts/swaps", icon: Repeat },
          { label: "Shift Requests", path: "/pay/shifts/requests", icon: ClipboardList },
          { label: "Shift Reports", path: "/pay/shifts/reports", icon: BarChart3 },
        ],
      },
      {
        label: "Timesheets",
        icon: ListChecks,
        permission: PERMISSIONS.PAY_TIMESHEETS_VIEW,
        children: [
          { label: "Weekly Timesheets", path: "/pay/timesheets/weekly", icon: CalendarRange },
          { label: "Monthly Timesheets", path: "/pay/timesheets/monthly", icon: CalendarDays },
          { label: "Project Timesheets", path: "/pay/timesheets/projects", icon: Briefcase },
          { label: "Approval Workflow", path: "/pay/timesheets/approvals", icon: Workflow },
          { label: "Timesheet Reports", path: "/pay/timesheets/reports", icon: BarChart3 },
          { label: "Missing Entries", path: "/pay/timesheets/missing", icon: Flag },
          { label: "Billable Hours", path: "/pay/timesheets/billable", icon: BadgeDollarSign },
          { label: "Productivity Reports", path: "/pay/timesheets/productivity", icon: TrendingUp },
        ],
      },
      {
        label: "Overtime",
        icon: Timer,
        permission: PERMISSIONS.PAY_OVERTIME_VIEW,
        children: [
          { label: "Overtime Requests", path: "/pay/overtime/requests", icon: ClipboardList },
          { label: "Approval Workflow", path: "/pay/overtime/approvals", icon: Workflow },
          { label: "Overtime Policies", path: "/pay/overtime/policies", icon: ScrollText },
          { label: "Overtime Reports", path: "/pay/overtime/reports", icon: BarChart3 },
          { label: "Overtime Analytics", path: "/pay/overtime/analytics", icon: BarChart },
        ],
      },
    ],
  },
  {
    label: "Pay · Insights",
    items: [
      {
        label: "Compliance",
        icon: ShieldCheck,
        permission: PERMISSIONS.PAY_COMPLIANCE_VIEW,
        children: [
          { label: "Compliance Dashboard", path: "/pay/compliance", icon: LayoutDashboard },
          { label: "Government Contributions", path: "/pay/compliance/contributions", icon: Landmark },
          { label: "Tax Compliance", path: "/pay/compliance/tax", icon: ReceiptText },
          { label: "Statutory Reports", path: "/pay/compliance/statutory", icon: FileText },
          { label: "Audit Reports", path: "/pay/compliance/audit", icon: FileSearch },
          { label: "Compliance Calendar", path: "/pay/compliance/calendar", icon: CalendarRange },
          { label: "Country Rules", path: "/pay/compliance/rules", icon: Scale },
        ],
      },
      {
        label: "Reports",
        icon: BarChart3,
        permission: PERMISSIONS.PAY_REPORTS_VIEW,
        children: [
          { label: "Payroll Reports", path: "/pay/reports/payroll", icon: Wallet },
          { label: "Salary Reports", path: "/pay/reports/salary", icon: BadgeDollarSign },
          { label: "Department Cost", path: "/pay/reports/dept-cost", icon: Building },
          { label: "Compensation Reports", path: "/pay/reports/compensation", icon: BadgeDollarSign },
          { label: "Benefits Reports", path: "/pay/reports/benefits", icon: Heart },
          { label: "Attendance Reports", path: "/pay/reports/attendance", icon: Clock },
          { label: "Leave Reports", path: "/pay/reports/leave", icon: PlaneTakeoff },
          { label: "Timesheet Reports", path: "/pay/reports/timesheets", icon: ListChecks },
          { label: "Overtime Reports", path: "/pay/reports/overtime", icon: Timer },
          { label: "Tax Reports", path: "/pay/reports/tax", icon: ReceiptText },
          { label: "Compliance Reports", path: "/pay/reports/compliance", icon: ShieldCheck },
          { label: "Executive Reports", path: "/pay/reports/executive", icon: BarChart3 },
        ],
      },
      {
        label: "Analytics",
        icon: LineChartIcon,
        permission: PERMISSIONS.PAY_ANALYTICS_VIEW,
        children: [
          { label: "Payroll Trends", path: "/pay/analytics/payroll", icon: LineChartIcon },
          { label: "Compensation Trends", path: "/pay/analytics/compensation", icon: BadgeDollarSign },
          { label: "Attendance Trends", path: "/pay/analytics/attendance", icon: Clock },
          { label: "Leave Trends", path: "/pay/analytics/leave", icon: PlaneTakeoff },
          { label: "Department Cost", path: "/pay/analytics/dept-cost", icon: Building },
          { label: "Salary Growth", path: "/pay/analytics/salary-growth", icon: TrendingUp },
          { label: "Headcount Cost", path: "/pay/analytics/headcount-cost", icon: Users },
          { label: "Benefit Utilization", path: "/pay/analytics/benefits", icon: Heart },
          { label: "Overtime Trends", path: "/pay/analytics/overtime", icon: Timer },
          { label: "Budget Utilization", path: "/pay/analytics/budget", icon: PieChart },
        ],
      },
    ],
  },


  {
    label: "Account",
    items: [
      {
        label: "Settings",
        icon: Settings,
        permission: PERMISSIONS.SETTINGS_VIEW,
        children: [
          { label: "Preferences", path: "/settings/preferences", icon: SlidersHorizontal },
          { label: "Security", path: "/settings/security", icon: Shield },
          { label: "Password", path: "/settings/password", icon: KeyRound },
          { label: "Two Factor Auth", path: "/settings/2fa", icon: Fingerprint },
          { label: "Sessions", path: "/settings/sessions", icon: Monitor },
          { label: "Privacy", path: "/settings/privacy", icon: EyeOff },
          { label: "General", path: "/settings", icon: Lock },
        ],
      },
    ],
  },
];

// Flattened list of all navigable pages. Used by the splat stub route and
// command palette so titles come from a single source.
export interface FlatNav {
  path: string;
  label: string;
  section: string;
  parent?: string;
  icon?: NavSection["items"][number]["icon"];
  permission?: string;
}

export const FLAT_NAV: FlatNav[] = NAVIGATION.flatMap((section) =>
  section.items.flatMap((item) => {
    const rows: FlatNav[] = [];
    if (item.path) {
      rows.push({
        path: item.path,
        label: item.label,
        section: section.label,
        icon: item.icon,
        permission: item.permission,
      });
    }
    if (item.children) {
      for (const child of item.children) {
        if (!child.path) continue;
        rows.push({
          path: child.path,
          label: child.label,
          section: section.label,
          parent: item.label,
          icon: child.icon ?? item.icon,
          permission: item.permission,
        });
      }
    }
    return rows;
  }),
);

export function findNav(path: string): FlatNav | undefined {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return FLAT_NAV.find((n) => n.path === normalized);
}
