// Central permission catalog. Every navigation item references a permission id.
// RBAC is enforced by matching User.permissions against these ids.
export const PERMISSIONS = {
  // ESS
  DASHBOARD_VIEW: "ess.dashboard.view",
  PROFILE_VIEW: "ess.profile.view",
  DOCUMENTS_VIEW: "ess.documents.view",
  ATTENDANCE_VIEW: "ess.attendance.view",
  LEAVE_VIEW: "ess.leave.view",
  PAYROLL_VIEW: "ess.payroll.view",
  BENEFITS_VIEW: "ess.benefits.view",
  ASSETS_VIEW: "ess.assets.view",
  LEARNING_VIEW: "ess.learning.view",
  CAREER_VIEW: "ess.career.view",
  ORG_VIEW: "ess.org.view",
  HELPDESK_VIEW: "ess.helpdesk.view",
  REQUESTS_VIEW: "ess.requests.view",
  NOTIFICATIONS_VIEW: "ess.notifications.view",
  SETTINGS_VIEW: "ess.settings.view",

  // HR Administration
  HR_DASHBOARD_VIEW: "hr.dashboard.view",
  HR_EMPLOYEES_VIEW: "hr.employees.view",
  HR_ORG_STRUCTURE_VIEW: "hr.orgstructure.view",
  HR_LIFECYCLE_VIEW: "hr.lifecycle.view",
  HR_RECRUITMENT_VIEW: "hr.recruitment.view",
  HR_ONBOARDING_VIEW: "hr.onboarding.view",
  HR_OFFBOARDING_VIEW: "hr.offboarding.view",
  HR_PERFORMANCE_VIEW: "hr.performance.view",
  HR_LND_VIEW: "hr.lnd.view",
  HR_COMPENSATION_VIEW: "hr.compensation.view",
  HR_WORKFORCE_VIEW: "hr.workforce.view",
  HR_LEAVE_ADMIN_VIEW: "hr.leaveadmin.view",
  HR_ATTENDANCE_ADMIN_VIEW: "hr.attendanceadmin.view",
  HR_DOCUMENTS_ADMIN_VIEW: "hr.documents.view",
  HR_COMPLIANCE_VIEW: "hr.compliance.view",
  HR_RELATIONS_VIEW: "hr.relations.view",
  HR_ENGAGEMENT_VIEW: "hr.engagement.view",
  HR_ANALYTICS_VIEW: "hr.analytics.view",
  HR_APPROVALS_VIEW: "hr.approvals.view",

  // System Administration & IT Management (Phase 3)
  ADMIN_DASHBOARD_VIEW: "admin.dashboard.view",
  ADMIN_ORG_VIEW: "admin.org.view",
  ADMIN_USERS_VIEW: "admin.users.view",
  ADMIN_ROLES_VIEW: "admin.roles.view",
  ADMIN_IAM_VIEW: "admin.iam.view",
  ADMIN_APPS_VIEW: "admin.apps.view",
  ADMIN_DEVICES_VIEW: "admin.devices.view",
  ADMIN_SOFTWARE_VIEW: "admin.software.view",
  ADMIN_ASSETS_VIEW: "admin.assets.view",
  ADMIN_WORKFLOWS_VIEW: "admin.workflows.view",
  ADMIN_SECURITY_VIEW: "admin.security.view",
  ADMIN_CONFIG_VIEW: "admin.config.view",
  ADMIN_INTEGRATIONS_VIEW: "admin.integrations.view",
  ADMIN_NOTIFICATIONS_VIEW: "admin.notifications.view",
  ADMIN_REPORTS_VIEW: "admin.reports.view",
  ADMIN_AI_VIEW: "admin.ai.view",

    // Payroll, Compensation, Benefits, Time (Phase 4)
  PAY_DASHBOARD_VIEW: "pay.dashboard.view",
  PAY_RUNS_VIEW: "pay.runs.view",
  PAY_COMPENSATION_VIEW: "pay.compensation.view",
  PAY_BENEFITS_VIEW: "pay.benefits.view",
  PAY_PAYSLIPS_VIEW: "pay.payslips.view",
  PAY_TAX_VIEW: "pay.tax.view",
  PAY_REIMBURSEMENTS_VIEW: "pay.reimbursements.view",
  PAY_LOANS_VIEW: "pay.loans.view",
  PAY_LEAVE_ADMIN_VIEW: "pay.leave.view",
  PAY_ATTENDANCE_VIEW: "pay.attendance.view",
  PAY_SHIFTS_VIEW: "pay.shifts.view",
  PAY_TIMESHEETS_VIEW: "pay.timesheets.view",
  PAY_OVERTIME_VIEW: "pay.overtime.view",
  PAY_COMPLIANCE_VIEW: "pay.compliance.view",
  PAY_REPORTS_VIEW: "pay.reports.view",
  PAY_ANALYTICS_VIEW: "pay.analytics.view",
  PAY_AI_VIEW: "pay.ai.view",
} as const;

export type PermissionId = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
