# Generated by Django 5.1.15 on 2026-07-25 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ess', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('employment', 'Employment'), ('education', 'Education'), ('certificate', 'Certificate'), ('tax', 'Tax'), ('medical', 'Medical')], max_length=16)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_by', models.CharField(default='Self', max_length=64)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ess.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
