# Generated by Django 5.1.15 on 2026-08-12 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ess', '0002_employee_organization_employment_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_grade', models.CharField(max_length=16)),
                ('to_grade', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=64)),
                ('effective', models.DateField()),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('approved', 'Approved'), ('on_hold', 'On hold'), ('rejected', 'Rejected')], default='recommended', max_length=16)),
                ('recommender', models.CharField(blank=True, max_length=128)),
                ('justification', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-effective',),
            },
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective', models.DateField()),
                ('previous_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('approver', models.CharField(blank=True, max_length=128)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-effective',),
            },
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=64)),
                ('min_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mid_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_avg_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('grade',),
                'unique_together': {('organization', 'grade', 'role')},
            },
        ),
    ]
