/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSessionExpiredRouteImport } from './routes/auth/session-expired'
import { Route as AuthUnauthorizedRouteImport } from './routes/auth/unauthorized'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAssetsDevicesRouteImport } from './routes/_app.assets.devices'
import { Route as AppAttendanceHistoryRouteImport } from './routes/_app.attendance.history'
import { Route as AppAttendanceTodayRouteImport } from './routes/_app.attendance.today'
import { Route as AppBenefitsExpensesRouteImport } from './routes/_app.benefits.expenses'
import { Route as AppCareerGoalsRouteImport } from './routes/_app.career.goals'
import { Route as AppHelpdeskTicketsRouteImport } from './routes/_app.helpdesk.tickets'
import { Route as AppHrIndexRouteImport } from './routes/_app.hr.index'
import { Route as AppHrApprovalsRouteImport } from './routes/_app.hr.approvals'
import { Route as AppHrEmployeesRouteImport } from './routes/_app.hr.employees'
import { Route as AppLearningCoursesRouteImport } from './routes/_app.learning.courses'
import { Route as AppLeaveIndexRouteImport } from './routes/_app.leave.index'
import { Route as AppLeaveApplyRouteImport } from './routes/_app.leave.apply'
import { Route as AppLeaveHistoryRouteImport } from './routes/_app.leave.history'
import { Route as AppLeaveHolidaysRouteImport } from './routes/_app.leave.holidays'
import { Route as AppOrgDirectoryRouteImport } from './routes/_app.org.directory'
import { Route as AppPayrollIndexRouteImport } from './routes/_app.payroll.index'
import { Route as AppPayrollPayslipsRouteImport } from './routes/_app.payroll.payslips'
import { Route as AppProfilePersonalRouteImport } from './routes/_app.profile.personal'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsPrivacyRouteImport } from './routes/_app.settings.privacy'
import { Route as AppHrAnalyticsDiversityRouteImport } from './routes/_app.hr.analytics.diversity'
import { Route as AppHrAnalyticsHeadcountRouteImport } from './routes/_app.hr.analytics.headcount'
import { Route as AppHrAttendanceAdminIndexRouteImport } from './routes/_app.hr.attendance-admin.index'
import { Route as AppHrCompensationBandsRouteImport } from './routes/_app.hr.compensation.bands'
import { Route as AppHrCompensationIncrementsRouteImport } from './routes/_app.hr.compensation.increments'
import { Route as AppHrCompensationPromotionsRouteImport } from './routes/_app.hr.compensation.promotions'
import { Route as AppHrComplianceIndexRouteImport } from './routes/_app.hr.compliance.index'
import { Route as AppHrComplianceAuditRouteImport } from './routes/_app.hr.compliance.audit'
import { Route as AppHrDocumentsPoliciesRouteImport } from './routes/_app.hr.documents.policies'
import { Route as AppHrEmployeesProfileRouteImport } from './routes/_app.hr.employees.profile'
import { Route as AppHrEngagementAnnouncementsRouteImport } from './routes/_app.hr.engagement.announcements'
import { Route as AppHrEngagementPulseRouteImport } from './routes/_app.hr.engagement.pulse'
import { Route as AppHrLeaveAdminPoliciesRouteImport } from './routes/_app.hr.leave-admin.policies'
import { Route as AppHrLndIndexRouteImport } from './routes/_app.hr.lnd.index'
import { Route as AppHrLndProgramsRouteImport } from './routes/_app.hr.lnd.programs'
import { Route as AppHrLndSkillsRouteImport } from './routes/_app.hr.lnd.skills'
import { Route as AppHrOffboardingResignationsRouteImport } from './routes/_app.hr.offboarding.resignations'
import { Route as AppHrOnboardingIndexRouteImport } from './routes/_app.hr.onboarding.index'
import { Route as AppHrOnboardingTasksRouteImport } from './routes/_app.hr.onboarding.tasks'
import { Route as AppHrOrgDepartmentsRouteImport } from './routes/_app.hr.org.departments'
import { Route as AppHrPerformanceAnalyticsRouteImport } from './routes/_app.hr.performance.analytics'
import { Route as AppHrPerformanceCompetenciesRouteImport } from './routes/_app.hr.performance.competencies'
import { Route as AppHrPerformanceCyclesRouteImport } from './routes/_app.hr.performance.cycles'
import { Route as AppHrPerformanceEmployeeReviewsRouteImport } from './routes/_app.hr.performance.employee-reviews'
import { Route as AppHrPerformanceGoalsRouteImport } from './routes/_app.hr.performance.goals'
import { Route as AppHrRecruitmentAnalyticsRouteImport } from './routes/_app.hr.recruitment.analytics'
import { Route as AppHrRecruitmentInterviewsRouteImport } from './routes/_app.hr.recruitment.interviews'
import { Route as AppHrRecruitmentOffersRouteImport } from './routes/_app.hr.recruitment.offers'
import { Route as AppHrRecruitmentPipelineRouteImport } from './routes/_app.hr.recruitment.pipeline'
import { Route as AppHrRecruitmentRequisitionsRouteImport } from './routes/_app.hr.recruitment.requisitions'
import { Route as AppHrRelationsGrievancesRouteImport } from './routes/_app.hr.relations.grievances'
import { Route as AppHrWorkforceIndexRouteImport } from './routes/_app.hr.workforce.index'
import { Route as AppHrWorkforceAttritionRouteImport } from './routes/_app.hr.workforce.attrition'
import { Route as AppHrWorkforceSuccessionRouteImport } from './routes/_app.hr.workforce.succession'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/auth/session-expired',
  path: '/auth/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsDevicesRoute = AppAssetsDevicesRouteImport.update({
  id: '/assets/devices',
  path: '/assets/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceHistoryRoute = AppAttendanceHistoryRouteImport.update({
  id: '/attendance/history',
  path: '/attendance/history',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceTodayRoute = AppAttendanceTodayRouteImport.update({
  id: '/attendance/today',
  path: '/attendance/today',
  getParentRoute: () => AppRoute,
} as any)
const AppBenefitsExpensesRoute = AppBenefitsExpensesRouteImport.update({
  id: '/benefits/expenses',
  path: '/benefits/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerGoalsRoute = AppCareerGoalsRouteImport.update({
  id: '/career/goals',
  path: '/career/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskTicketsRoute = AppHelpdeskTicketsRouteImport.update({
  id: '/helpdesk/tickets',
  path: '/helpdesk/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrApprovalsRoute = AppHrApprovalsRouteImport.update({
  id: '/hr/approvals',
  path: '/hr/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningCoursesRoute = AppLearningCoursesRouteImport.update({
  id: '/learning/courses',
  path: '/learning/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveIndexRoute = AppLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApplyRoute = AppLeaveApplyRouteImport.update({
  id: '/leave/apply',
  path: '/leave/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveHistoryRoute = AppLeaveHistoryRouteImport.update({
  id: '/leave/history',
  path: '/leave/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveHolidaysRoute = AppLeaveHolidaysRouteImport.update({
  id: '/leave/holidays',
  path: '/leave/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgDirectoryRoute = AppOrgDirectoryRouteImport.update({
  id: '/org/directory',
  path: '/org/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollPayslipsRoute = AppPayrollPayslipsRouteImport.update({
  id: '/payroll/payslips',
  path: '/payroll/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilePersonalRoute = AppProfilePersonalRouteImport.update({
  id: '/profile/personal',
  path: '/profile/personal',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAnalyticsDiversityRoute = AppHrAnalyticsDiversityRouteImport.update({
  id: '/hr/analytics/diversity',
  path: '/hr/analytics/diversity',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAnalyticsHeadcountRoute = AppHrAnalyticsHeadcountRouteImport.update({
  id: '/hr/analytics/headcount',
  path: '/hr/analytics/headcount',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAttendanceAdminIndexRoute =
  AppHrAttendanceAdminIndexRouteImport.update({
    id: '/hr/attendance-admin/',
    path: '/hr/attendance-admin/',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrCompensationBandsRoute = AppHrCompensationBandsRouteImport.update({
  id: '/hr/compensation/bands',
  path: '/hr/compensation/bands',
  getParentRoute: () => AppRoute,
} as any)
const AppHrCompensationIncrementsRoute =
  AppHrCompensationIncrementsRouteImport.update({
    id: '/hr/compensation/increments',
    path: '/hr/compensation/increments',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrCompensationPromotionsRoute =
  AppHrCompensationPromotionsRouteImport.update({
    id: '/hr/compensation/promotions',
    path: '/hr/compensation/promotions',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrComplianceIndexRoute = AppHrComplianceIndexRouteImport.update({
  id: '/hr/compliance/',
  path: '/hr/compliance/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrComplianceAuditRoute = AppHrComplianceAuditRouteImport.update({
  id: '/hr/compliance/audit',
  path: '/hr/compliance/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppHrDocumentsPoliciesRoute = AppHrDocumentsPoliciesRouteImport.update({
  id: '/hr/documents/policies',
  path: '/hr/documents/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesProfileRoute = AppHrEmployeesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppHrEmployeesRoute,
} as any)
const AppHrEngagementAnnouncementsRoute =
  AppHrEngagementAnnouncementsRouteImport.update({
    id: '/hr/engagement/announcements',
    path: '/hr/engagement/announcements',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrEngagementPulseRoute = AppHrEngagementPulseRouteImport.update({
  id: '/hr/engagement/pulse',
  path: '/hr/engagement/pulse',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLeaveAdminPoliciesRoute = AppHrLeaveAdminPoliciesRouteImport.update({
  id: '/hr/leave-admin/policies',
  path: '/hr/leave-admin/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLndIndexRoute = AppHrLndIndexRouteImport.update({
  id: '/hr/lnd/',
  path: '/hr/lnd/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLndProgramsRoute = AppHrLndProgramsRouteImport.update({
  id: '/hr/lnd/programs',
  path: '/hr/lnd/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLndSkillsRoute = AppHrLndSkillsRouteImport.update({
  id: '/hr/lnd/skills',
  path: '/hr/lnd/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppHrOffboardingResignationsRoute =
  AppHrOffboardingResignationsRouteImport.update({
    id: '/hr/offboarding/resignations',
    path: '/hr/offboarding/resignations',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrOnboardingIndexRoute = AppHrOnboardingIndexRouteImport.update({
  id: '/hr/onboarding/',
  path: '/hr/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrOnboardingTasksRoute = AppHrOnboardingTasksRouteImport.update({
  id: '/hr/onboarding/tasks',
  path: '/hr/onboarding/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppHrOrgDepartmentsRoute = AppHrOrgDepartmentsRouteImport.update({
  id: '/hr/org/departments',
  path: '/hr/org/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPerformanceAnalyticsRoute =
  AppHrPerformanceAnalyticsRouteImport.update({
    id: '/hr/performance/analytics',
    path: '/hr/performance/analytics',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrPerformanceCompetenciesRoute =
  AppHrPerformanceCompetenciesRouteImport.update({
    id: '/hr/performance/competencies',
    path: '/hr/performance/competencies',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrPerformanceCyclesRoute = AppHrPerformanceCyclesRouteImport.update({
  id: '/hr/performance/cycles',
  path: '/hr/performance/cycles',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPerformanceEmployeeReviewsRoute =
  AppHrPerformanceEmployeeReviewsRouteImport.update({
    id: '/hr/performance/employee-reviews',
    path: '/hr/performance/employee-reviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrPerformanceGoalsRoute = AppHrPerformanceGoalsRouteImport.update({
  id: '/hr/performance/goals',
  path: '/hr/performance/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRecruitmentAnalyticsRoute =
  AppHrRecruitmentAnalyticsRouteImport.update({
    id: '/hr/recruitment/analytics',
    path: '/hr/recruitment/analytics',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrRecruitmentInterviewsRoute =
  AppHrRecruitmentInterviewsRouteImport.update({
    id: '/hr/recruitment/interviews',
    path: '/hr/recruitment/interviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrRecruitmentOffersRoute = AppHrRecruitmentOffersRouteImport.update({
  id: '/hr/recruitment/offers',
  path: '/hr/recruitment/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRecruitmentPipelineRoute =
  AppHrRecruitmentPipelineRouteImport.update({
    id: '/hr/recruitment/pipeline',
    path: '/hr/recruitment/pipeline',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrRecruitmentRequisitionsRoute =
  AppHrRecruitmentRequisitionsRouteImport.update({
    id: '/hr/recruitment/requisitions',
    path: '/hr/recruitment/requisitions',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrRelationsGrievancesRoute =
  AppHrRelationsGrievancesRouteImport.update({
    id: '/hr/relations/grievances',
    path: '/hr/relations/grievances',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrWorkforceIndexRoute = AppHrWorkforceIndexRouteImport.update({
  id: '/hr/workforce/',
  path: '/hr/workforce/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrWorkforceAttritionRoute = AppHrWorkforceAttritionRouteImport.update({
  id: '/hr/workforce/attrition',
  path: '/hr/workforce/attrition',
  getParentRoute: () => AppRoute,
} as any)
const AppHrWorkforceSuccessionRoute =
  AppHrWorkforceSuccessionRouteImport.update({
    id: '/hr/workforce/succession',
    path: '/hr/workforce/succession',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/documents': typeof AppDocumentsRoute
  '/notifications': typeof AppNotificationsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/assets/devices': typeof AppAssetsDevicesRoute
  '/attendance/history': typeof AppAttendanceHistoryRoute
  '/attendance/today': typeof AppAttendanceTodayRoute
  '/benefits/expenses': typeof AppBenefitsExpensesRoute
  '/career/goals': typeof AppCareerGoalsRoute
  '/helpdesk/tickets': typeof AppHelpdeskTicketsRoute
  '/hr/approvals': typeof AppHrApprovalsRoute
  '/hr/employees': typeof AppHrEmployeesRouteWithChildren
  '/learning/courses': typeof AppLearningCoursesRoute
  '/leave/apply': typeof AppLeaveApplyRoute
  '/leave/history': typeof AppLeaveHistoryRoute
  '/leave/holidays': typeof AppLeaveHolidaysRoute
  '/org/directory': typeof AppOrgDirectoryRoute
  '/payroll/payslips': typeof AppPayrollPayslipsRoute
  '/profile/personal': typeof AppProfilePersonalRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/admin/': typeof AppAdminIndexRoute
  '/hr/': typeof AppHrIndexRoute
  '/leave/': typeof AppLeaveIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/hr/analytics/diversity': typeof AppHrAnalyticsDiversityRoute
  '/hr/analytics/headcount': typeof AppHrAnalyticsHeadcountRoute
  '/hr/compensation/bands': typeof AppHrCompensationBandsRoute
  '/hr/compensation/increments': typeof AppHrCompensationIncrementsRoute
  '/hr/compensation/promotions': typeof AppHrCompensationPromotionsRoute
  '/hr/compliance/audit': typeof AppHrComplianceAuditRoute
  '/hr/documents/policies': typeof AppHrDocumentsPoliciesRoute
  '/hr/employees/profile': typeof AppHrEmployeesProfileRoute
  '/hr/engagement/announcements': typeof AppHrEngagementAnnouncementsRoute
  '/hr/engagement/pulse': typeof AppHrEngagementPulseRoute
  '/hr/leave-admin/policies': typeof AppHrLeaveAdminPoliciesRoute
  '/hr/lnd/programs': typeof AppHrLndProgramsRoute
  '/hr/lnd/skills': typeof AppHrLndSkillsRoute
  '/hr/offboarding/resignations': typeof AppHrOffboardingResignationsRoute
  '/hr/onboarding/tasks': typeof AppHrOnboardingTasksRoute
  '/hr/org/departments': typeof AppHrOrgDepartmentsRoute
  '/hr/performance/analytics': typeof AppHrPerformanceAnalyticsRoute
  '/hr/performance/competencies': typeof AppHrPerformanceCompetenciesRoute
  '/hr/performance/cycles': typeof AppHrPerformanceCyclesRoute
  '/hr/performance/employee-reviews': typeof AppHrPerformanceEmployeeReviewsRoute
  '/hr/performance/goals': typeof AppHrPerformanceGoalsRoute
  '/hr/recruitment/analytics': typeof AppHrRecruitmentAnalyticsRoute
  '/hr/recruitment/interviews': typeof AppHrRecruitmentInterviewsRoute
  '/hr/recruitment/offers': typeof AppHrRecruitmentOffersRoute
  '/hr/recruitment/pipeline': typeof AppHrRecruitmentPipelineRoute
  '/hr/recruitment/requisitions': typeof AppHrRecruitmentRequisitionsRoute
  '/hr/relations/grievances': typeof AppHrRelationsGrievancesRoute
  '/hr/workforce/attrition': typeof AppHrWorkforceAttritionRoute
  '/hr/workforce/succession': typeof AppHrWorkforceSuccessionRoute
  '/hr/attendance-admin/': typeof AppHrAttendanceAdminIndexRoute
  '/hr/compliance/': typeof AppHrComplianceIndexRoute
  '/hr/lnd/': typeof AppHrLndIndexRoute
  '/hr/onboarding/': typeof AppHrOnboardingIndexRoute
  '/hr/workforce/': typeof AppHrWorkforceIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof AppSplatRoute
  '/documents': typeof AppDocumentsRoute
  '/notifications': typeof AppNotificationsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/': typeof AppIndexRoute
  '/assets/devices': typeof AppAssetsDevicesRoute
  '/attendance/history': typeof AppAttendanceHistoryRoute
  '/attendance/today': typeof AppAttendanceTodayRoute
  '/benefits/expenses': typeof AppBenefitsExpensesRoute
  '/career/goals': typeof AppCareerGoalsRoute
  '/helpdesk/tickets': typeof AppHelpdeskTicketsRoute
  '/hr/approvals': typeof AppHrApprovalsRoute
  '/hr/employees': typeof AppHrEmployeesRouteWithChildren
  '/learning/courses': typeof AppLearningCoursesRoute
  '/leave/apply': typeof AppLeaveApplyRoute
  '/leave/history': typeof AppLeaveHistoryRoute
  '/leave/holidays': typeof AppLeaveHolidaysRoute
  '/org/directory': typeof AppOrgDirectoryRoute
  '/payroll/payslips': typeof AppPayrollPayslipsRoute
  '/profile/personal': typeof AppProfilePersonalRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/admin': typeof AppAdminIndexRoute
  '/hr': typeof AppHrIndexRoute
  '/leave': typeof AppLeaveIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/hr/analytics/diversity': typeof AppHrAnalyticsDiversityRoute
  '/hr/analytics/headcount': typeof AppHrAnalyticsHeadcountRoute
  '/hr/compensation/bands': typeof AppHrCompensationBandsRoute
  '/hr/compensation/increments': typeof AppHrCompensationIncrementsRoute
  '/hr/compensation/promotions': typeof AppHrCompensationPromotionsRoute
  '/hr/compliance/audit': typeof AppHrComplianceAuditRoute
  '/hr/documents/policies': typeof AppHrDocumentsPoliciesRoute
  '/hr/employees/profile': typeof AppHrEmployeesProfileRoute
  '/hr/engagement/announcements': typeof AppHrEngagementAnnouncementsRoute
  '/hr/engagement/pulse': typeof AppHrEngagementPulseRoute
  '/hr/leave-admin/policies': typeof AppHrLeaveAdminPoliciesRoute
  '/hr/lnd/programs': typeof AppHrLndProgramsRoute
  '/hr/lnd/skills': typeof AppHrLndSkillsRoute
  '/hr/offboarding/resignations': typeof AppHrOffboardingResignationsRoute
  '/hr/onboarding/tasks': typeof AppHrOnboardingTasksRoute
  '/hr/org/departments': typeof AppHrOrgDepartmentsRoute
  '/hr/performance/analytics': typeof AppHrPerformanceAnalyticsRoute
  '/hr/performance/competencies': typeof AppHrPerformanceCompetenciesRoute
  '/hr/performance/cycles': typeof AppHrPerformanceCyclesRoute
  '/hr/performance/employee-reviews': typeof AppHrPerformanceEmployeeReviewsRoute
  '/hr/performance/goals': typeof AppHrPerformanceGoalsRoute
  '/hr/recruitment/analytics': typeof AppHrRecruitmentAnalyticsRoute
  '/hr/recruitment/interviews': typeof AppHrRecruitmentInterviewsRoute
  '/hr/recruitment/offers': typeof AppHrRecruitmentOffersRoute
  '/hr/recruitment/pipeline': typeof AppHrRecruitmentPipelineRoute
  '/hr/recruitment/requisitions': typeof AppHrRecruitmentRequisitionsRoute
  '/hr/relations/grievances': typeof AppHrRelationsGrievancesRoute
  '/hr/workforce/attrition': typeof AppHrWorkforceAttritionRoute
  '/hr/workforce/succession': typeof AppHrWorkforceSuccessionRoute
  '/hr/attendance-admin': typeof AppHrAttendanceAdminIndexRoute
  '/hr/compliance': typeof AppHrComplianceIndexRoute
  '/hr/lnd': typeof AppHrLndIndexRoute
  '/hr/onboarding': typeof AppHrOnboardingIndexRoute
  '/hr/workforce': typeof AppHrWorkforceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/devices': typeof AppAssetsDevicesRoute
  '/_app/attendance/history': typeof AppAttendanceHistoryRoute
  '/_app/attendance/today': typeof AppAttendanceTodayRoute
  '/_app/benefits/expenses': typeof AppBenefitsExpensesRoute
  '/_app/career/goals': typeof AppCareerGoalsRoute
  '/_app/helpdesk/tickets': typeof AppHelpdeskTicketsRoute
  '/_app/hr/approvals': typeof AppHrApprovalsRoute
  '/_app/hr/employees': typeof AppHrEmployeesRouteWithChildren
  '/_app/learning/courses': typeof AppLearningCoursesRoute
  '/_app/leave/apply': typeof AppLeaveApplyRoute
  '/_app/leave/history': typeof AppLeaveHistoryRoute
  '/_app/leave/holidays': typeof AppLeaveHolidaysRoute
  '/_app/org/directory': typeof AppOrgDirectoryRoute
  '/_app/payroll/payslips': typeof AppPayrollPayslipsRoute
  '/_app/profile/personal': typeof AppProfilePersonalRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/hr/': typeof AppHrIndexRoute
  '/_app/leave/': typeof AppLeaveIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/hr/analytics/diversity': typeof AppHrAnalyticsDiversityRoute
  '/_app/hr/analytics/headcount': typeof AppHrAnalyticsHeadcountRoute
  '/_app/hr/compensation/bands': typeof AppHrCompensationBandsRoute
  '/_app/hr/compensation/increments': typeof AppHrCompensationIncrementsRoute
  '/_app/hr/compensation/promotions': typeof AppHrCompensationPromotionsRoute
  '/_app/hr/compliance/audit': typeof AppHrComplianceAuditRoute
  '/_app/hr/documents/policies': typeof AppHrDocumentsPoliciesRoute
  '/_app/hr/employees/profile': typeof AppHrEmployeesProfileRoute
  '/_app/hr/engagement/announcements': typeof AppHrEngagementAnnouncementsRoute
  '/_app/hr/engagement/pulse': typeof AppHrEngagementPulseRoute
  '/_app/hr/leave-admin/policies': typeof AppHrLeaveAdminPoliciesRoute
  '/_app/hr/lnd/programs': typeof AppHrLndProgramsRoute
  '/_app/hr/lnd/skills': typeof AppHrLndSkillsRoute
  '/_app/hr/offboarding/resignations': typeof AppHrOffboardingResignationsRoute
  '/_app/hr/onboarding/tasks': typeof AppHrOnboardingTasksRoute
  '/_app/hr/org/departments': typeof AppHrOrgDepartmentsRoute
  '/_app/hr/performance/analytics': typeof AppHrPerformanceAnalyticsRoute
  '/_app/hr/performance/competencies': typeof AppHrPerformanceCompetenciesRoute
  '/_app/hr/performance/cycles': typeof AppHrPerformanceCyclesRoute
  '/_app/hr/performance/employee-reviews': typeof AppHrPerformanceEmployeeReviewsRoute
  '/_app/hr/performance/goals': typeof AppHrPerformanceGoalsRoute
  '/_app/hr/recruitment/analytics': typeof AppHrRecruitmentAnalyticsRoute
  '/_app/hr/recruitment/interviews': typeof AppHrRecruitmentInterviewsRoute
  '/_app/hr/recruitment/offers': typeof AppHrRecruitmentOffersRoute
  '/_app/hr/recruitment/pipeline': typeof AppHrRecruitmentPipelineRoute
  '/_app/hr/recruitment/requisitions': typeof AppHrRecruitmentRequisitionsRoute
  '/_app/hr/relations/grievances': typeof AppHrRelationsGrievancesRoute
  '/_app/hr/workforce/attrition': typeof AppHrWorkforceAttritionRoute
  '/_app/hr/workforce/succession': typeof AppHrWorkforceSuccessionRoute
  '/_app/hr/attendance-admin/': typeof AppHrAttendanceAdminIndexRoute
  '/_app/hr/compliance/': typeof AppHrComplianceIndexRoute
  '/_app/hr/lnd/': typeof AppHrLndIndexRoute
  '/_app/hr/onboarding/': typeof AppHrOnboardingIndexRoute
  '/_app/hr/workforce/': typeof AppHrWorkforceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/documents'
    | '/notifications'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/auth/unauthorized'
    | '/auth/verify-email'
    | '/assets/devices'
    | '/attendance/history'
    | '/attendance/today'
    | '/benefits/expenses'
    | '/career/goals'
    | '/helpdesk/tickets'
    | '/hr/approvals'
    | '/hr/employees'
    | '/learning/courses'
    | '/leave/apply'
    | '/leave/history'
    | '/leave/holidays'
    | '/org/directory'
    | '/payroll/payslips'
    | '/profile/personal'
    | '/settings/privacy'
    | '/admin/'
    | '/hr/'
    | '/leave/'
    | '/payroll/'
    | '/settings/'
    | '/hr/analytics/diversity'
    | '/hr/analytics/headcount'
    | '/hr/compensation/bands'
    | '/hr/compensation/increments'
    | '/hr/compensation/promotions'
    | '/hr/compliance/audit'
    | '/hr/documents/policies'
    | '/hr/employees/profile'
    | '/hr/engagement/announcements'
    | '/hr/engagement/pulse'
    | '/hr/leave-admin/policies'
    | '/hr/lnd/programs'
    | '/hr/lnd/skills'
    | '/hr/offboarding/resignations'
    | '/hr/onboarding/tasks'
    | '/hr/org/departments'
    | '/hr/performance/analytics'
    | '/hr/performance/competencies'
    | '/hr/performance/cycles'
    | '/hr/performance/employee-reviews'
    | '/hr/performance/goals'
    | '/hr/recruitment/analytics'
    | '/hr/recruitment/interviews'
    | '/hr/recruitment/offers'
    | '/hr/recruitment/pipeline'
    | '/hr/recruitment/requisitions'
    | '/hr/relations/grievances'
    | '/hr/workforce/attrition'
    | '/hr/workforce/succession'
    | '/hr/attendance-admin/'
    | '/hr/compliance/'
    | '/hr/lnd/'
    | '/hr/onboarding/'
    | '/hr/workforce/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/documents'
    | '/notifications'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/auth/unauthorized'
    | '/auth/verify-email'
    | '/'
    | '/assets/devices'
    | '/attendance/history'
    | '/attendance/today'
    | '/benefits/expenses'
    | '/career/goals'
    | '/helpdesk/tickets'
    | '/hr/approvals'
    | '/hr/employees'
    | '/learning/courses'
    | '/leave/apply'
    | '/leave/history'
    | '/leave/holidays'
    | '/org/directory'
    | '/payroll/payslips'
    | '/profile/personal'
    | '/settings/privacy'
    | '/admin'
    | '/hr'
    | '/leave'
    | '/payroll'
    | '/settings'
    | '/hr/analytics/diversity'
    | '/hr/analytics/headcount'
    | '/hr/compensation/bands'
    | '/hr/compensation/increments'
    | '/hr/compensation/promotions'
    | '/hr/compliance/audit'
    | '/hr/documents/policies'
    | '/hr/employees/profile'
    | '/hr/engagement/announcements'
    | '/hr/engagement/pulse'
    | '/hr/leave-admin/policies'
    | '/hr/lnd/programs'
    | '/hr/lnd/skills'
    | '/hr/offboarding/resignations'
    | '/hr/onboarding/tasks'
    | '/hr/org/departments'
    | '/hr/performance/analytics'
    | '/hr/performance/competencies'
    | '/hr/performance/cycles'
    | '/hr/performance/employee-reviews'
    | '/hr/performance/goals'
    | '/hr/recruitment/analytics'
    | '/hr/recruitment/interviews'
    | '/hr/recruitment/offers'
    | '/hr/recruitment/pipeline'
    | '/hr/recruitment/requisitions'
    | '/hr/relations/grievances'
    | '/hr/workforce/attrition'
    | '/hr/workforce/succession'
    | '/hr/attendance-admin'
    | '/hr/compliance'
    | '/hr/lnd'
    | '/hr/onboarding'
    | '/hr/workforce'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$'
    | '/_app/documents'
    | '/_app/notifications'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/auth/unauthorized'
    | '/auth/verify-email'
    | '/_app/'
    | '/_app/assets/devices'
    | '/_app/attendance/history'
    | '/_app/attendance/today'
    | '/_app/benefits/expenses'
    | '/_app/career/goals'
    | '/_app/helpdesk/tickets'
    | '/_app/hr/approvals'
    | '/_app/hr/employees'
    | '/_app/learning/courses'
    | '/_app/leave/apply'
    | '/_app/leave/history'
    | '/_app/leave/holidays'
    | '/_app/org/directory'
    | '/_app/payroll/payslips'
    | '/_app/profile/personal'
    | '/_app/settings/privacy'
    | '/_app/admin/'
    | '/_app/hr/'
    | '/_app/leave/'
    | '/_app/payroll/'
    | '/_app/settings/'
    | '/_app/hr/analytics/diversity'
    | '/_app/hr/analytics/headcount'
    | '/_app/hr/compensation/bands'
    | '/_app/hr/compensation/increments'
    | '/_app/hr/compensation/promotions'
    | '/_app/hr/compliance/audit'
    | '/_app/hr/documents/policies'
    | '/_app/hr/employees/profile'
    | '/_app/hr/engagement/announcements'
    | '/_app/hr/engagement/pulse'
    | '/_app/hr/leave-admin/policies'
    | '/_app/hr/lnd/programs'
    | '/_app/hr/lnd/skills'
    | '/_app/hr/offboarding/resignations'
    | '/_app/hr/onboarding/tasks'
    | '/_app/hr/org/departments'
    | '/_app/hr/performance/analytics'
    | '/_app/hr/performance/competencies'
    | '/_app/hr/performance/cycles'
    | '/_app/hr/performance/employee-reviews'
    | '/_app/hr/performance/goals'
    | '/_app/hr/recruitment/analytics'
    | '/_app/hr/recruitment/interviews'
    | '/_app/hr/recruitment/offers'
    | '/_app/hr/recruitment/pipeline'
    | '/_app/hr/recruitment/requisitions'
    | '/_app/hr/relations/grievances'
    | '/_app/hr/workforce/attrition'
    | '/_app/hr/workforce/succession'
    | '/_app/hr/attendance-admin/'
    | '/_app/hr/compliance/'
    | '/_app/hr/lnd/'
    | '/_app/hr/onboarding/'
    | '/_app/hr/workforce/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/session-expired': {
      id: '/auth/session-expired'
      path: '/auth/session-expired'
      fullPath: '/auth/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/unauthorized': {
      id: '/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/devices': {
      id: '/_app/assets/devices'
      path: '/assets/devices'
      fullPath: '/assets/devices'
      preLoaderRoute: typeof AppAssetsDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/history': {
      id: '/_app/attendance/history'
      path: '/attendance/history'
      fullPath: '/attendance/history'
      preLoaderRoute: typeof AppAttendanceHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/today': {
      id: '/_app/attendance/today'
      path: '/attendance/today'
      fullPath: '/attendance/today'
      preLoaderRoute: typeof AppAttendanceTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/benefits/expenses': {
      id: '/_app/benefits/expenses'
      path: '/benefits/expenses'
      fullPath: '/benefits/expenses'
      preLoaderRoute: typeof AppBenefitsExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career/goals': {
      id: '/_app/career/goals'
      path: '/career/goals'
      fullPath: '/career/goals'
      preLoaderRoute: typeof AppCareerGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/helpdesk/tickets': {
      id: '/_app/helpdesk/tickets'
      path: '/helpdesk/tickets'
      fullPath: '/helpdesk/tickets'
      preLoaderRoute: typeof AppHelpdeskTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/': {
      id: '/_app/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/approvals': {
      id: '/_app/hr/approvals'
      path: '/hr/approvals'
      fullPath: '/hr/approvals'
      preLoaderRoute: typeof AppHrApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees': {
      id: '/_app/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning/courses': {
      id: '/_app/learning/courses'
      path: '/learning/courses'
      fullPath: '/learning/courses'
      preLoaderRoute: typeof AppLearningCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/': {
      id: '/_app/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof AppLeaveIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/apply': {
      id: '/_app/leave/apply'
      path: '/leave/apply'
      fullPath: '/leave/apply'
      preLoaderRoute: typeof AppLeaveApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/history': {
      id: '/_app/leave/history'
      path: '/leave/history'
      fullPath: '/leave/history'
      preLoaderRoute: typeof AppLeaveHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/holidays': {
      id: '/_app/leave/holidays'
      path: '/leave/holidays'
      fullPath: '/leave/holidays'
      preLoaderRoute: typeof AppLeaveHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/directory': {
      id: '/_app/org/directory'
      path: '/org/directory'
      fullPath: '/org/directory'
      preLoaderRoute: typeof AppOrgDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/payslips': {
      id: '/_app/payroll/payslips'
      path: '/payroll/payslips'
      fullPath: '/payroll/payslips'
      preLoaderRoute: typeof AppPayrollPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/personal': {
      id: '/_app/profile/personal'
      path: '/profile/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof AppProfilePersonalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/analytics/diversity': {
      id: '/_app/hr/analytics/diversity'
      path: '/hr/analytics/diversity'
      fullPath: '/hr/analytics/diversity'
      preLoaderRoute: typeof AppHrAnalyticsDiversityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/analytics/headcount': {
      id: '/_app/hr/analytics/headcount'
      path: '/hr/analytics/headcount'
      fullPath: '/hr/analytics/headcount'
      preLoaderRoute: typeof AppHrAnalyticsHeadcountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/attendance-admin/': {
      id: '/_app/hr/attendance-admin/'
      path: '/hr/attendance-admin'
      fullPath: '/hr/attendance-admin/'
      preLoaderRoute: typeof AppHrAttendanceAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/compensation/bands': {
      id: '/_app/hr/compensation/bands'
      path: '/hr/compensation/bands'
      fullPath: '/hr/compensation/bands'
      preLoaderRoute: typeof AppHrCompensationBandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/compensation/increments': {
      id: '/_app/hr/compensation/increments'
      path: '/hr/compensation/increments'
      fullPath: '/hr/compensation/increments'
      preLoaderRoute: typeof AppHrCompensationIncrementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/compensation/promotions': {
      id: '/_app/hr/compensation/promotions'
      path: '/hr/compensation/promotions'
      fullPath: '/hr/compensation/promotions'
      preLoaderRoute: typeof AppHrCompensationPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/compliance/': {
      id: '/_app/hr/compliance/'
      path: '/hr/compliance'
      fullPath: '/hr/compliance/'
      preLoaderRoute: typeof AppHrComplianceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/compliance/audit': {
      id: '/_app/hr/compliance/audit'
      path: '/hr/compliance/audit'
      fullPath: '/hr/compliance/audit'
      preLoaderRoute: typeof AppHrComplianceAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/documents/policies': {
      id: '/_app/hr/documents/policies'
      path: '/hr/documents/policies'
      fullPath: '/hr/documents/policies'
      preLoaderRoute: typeof AppHrDocumentsPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees/profile': {
      id: '/_app/hr/employees/profile'
      path: '/profile'
      fullPath: '/hr/employees/profile'
      preLoaderRoute: typeof AppHrEmployeesProfileRouteImport
      parentRoute: typeof AppHrEmployeesRoute
    }
    '/_app/hr/engagement/announcements': {
      id: '/_app/hr/engagement/announcements'
      path: '/hr/engagement/announcements'
      fullPath: '/hr/engagement/announcements'
      preLoaderRoute: typeof AppHrEngagementAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/engagement/pulse': {
      id: '/_app/hr/engagement/pulse'
      path: '/hr/engagement/pulse'
      fullPath: '/hr/engagement/pulse'
      preLoaderRoute: typeof AppHrEngagementPulseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/leave-admin/policies': {
      id: '/_app/hr/leave-admin/policies'
      path: '/hr/leave-admin/policies'
      fullPath: '/hr/leave-admin/policies'
      preLoaderRoute: typeof AppHrLeaveAdminPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/lnd/': {
      id: '/_app/hr/lnd/'
      path: '/hr/lnd'
      fullPath: '/hr/lnd/'
      preLoaderRoute: typeof AppHrLndIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/lnd/programs': {
      id: '/_app/hr/lnd/programs'
      path: '/hr/lnd/programs'
      fullPath: '/hr/lnd/programs'
      preLoaderRoute: typeof AppHrLndProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/lnd/skills': {
      id: '/_app/hr/lnd/skills'
      path: '/hr/lnd/skills'
      fullPath: '/hr/lnd/skills'
      preLoaderRoute: typeof AppHrLndSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/offboarding/resignations': {
      id: '/_app/hr/offboarding/resignations'
      path: '/hr/offboarding/resignations'
      fullPath: '/hr/offboarding/resignations'
      preLoaderRoute: typeof AppHrOffboardingResignationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/onboarding/': {
      id: '/_app/hr/onboarding/'
      path: '/hr/onboarding'
      fullPath: '/hr/onboarding/'
      preLoaderRoute: typeof AppHrOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/onboarding/tasks': {
      id: '/_app/hr/onboarding/tasks'
      path: '/hr/onboarding/tasks'
      fullPath: '/hr/onboarding/tasks'
      preLoaderRoute: typeof AppHrOnboardingTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/org/departments': {
      id: '/_app/hr/org/departments'
      path: '/hr/org/departments'
      fullPath: '/hr/org/departments'
      preLoaderRoute: typeof AppHrOrgDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/performance/analytics': {
      id: '/_app/hr/performance/analytics'
      path: '/hr/performance/analytics'
      fullPath: '/hr/performance/analytics'
      preLoaderRoute: typeof AppHrPerformanceAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/performance/competencies': {
      id: '/_app/hr/performance/competencies'
      path: '/hr/performance/competencies'
      fullPath: '/hr/performance/competencies'
      preLoaderRoute: typeof AppHrPerformanceCompetenciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/performance/cycles': {
      id: '/_app/hr/performance/cycles'
      path: '/hr/performance/cycles'
      fullPath: '/hr/performance/cycles'
      preLoaderRoute: typeof AppHrPerformanceCyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/performance/employee-reviews': {
      id: '/_app/hr/performance/employee-reviews'
      path: '/hr/performance/employee-reviews'
      fullPath: '/hr/performance/employee-reviews'
      preLoaderRoute: typeof AppHrPerformanceEmployeeReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/performance/goals': {
      id: '/_app/hr/performance/goals'
      path: '/hr/performance/goals'
      fullPath: '/hr/performance/goals'
      preLoaderRoute: typeof AppHrPerformanceGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/recruitment/analytics': {
      id: '/_app/hr/recruitment/analytics'
      path: '/hr/recruitment/analytics'
      fullPath: '/hr/recruitment/analytics'
      preLoaderRoute: typeof AppHrRecruitmentAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/recruitment/interviews': {
      id: '/_app/hr/recruitment/interviews'
      path: '/hr/recruitment/interviews'
      fullPath: '/hr/recruitment/interviews'
      preLoaderRoute: typeof AppHrRecruitmentInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/recruitment/offers': {
      id: '/_app/hr/recruitment/offers'
      path: '/hr/recruitment/offers'
      fullPath: '/hr/recruitment/offers'
      preLoaderRoute: typeof AppHrRecruitmentOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/recruitment/pipeline': {
      id: '/_app/hr/recruitment/pipeline'
      path: '/hr/recruitment/pipeline'
      fullPath: '/hr/recruitment/pipeline'
      preLoaderRoute: typeof AppHrRecruitmentPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/recruitment/requisitions': {
      id: '/_app/hr/recruitment/requisitions'
      path: '/hr/recruitment/requisitions'
      fullPath: '/hr/recruitment/requisitions'
      preLoaderRoute: typeof AppHrRecruitmentRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/relations/grievances': {
      id: '/_app/hr/relations/grievances'
      path: '/hr/relations/grievances'
      fullPath: '/hr/relations/grievances'
      preLoaderRoute: typeof AppHrRelationsGrievancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/workforce/': {
      id: '/_app/hr/workforce/'
      path: '/hr/workforce'
      fullPath: '/hr/workforce/'
      preLoaderRoute: typeof AppHrWorkforceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/workforce/attrition': {
      id: '/_app/hr/workforce/attrition'
      path: '/hr/workforce/attrition'
      fullPath: '/hr/workforce/attrition'
      preLoaderRoute: typeof AppHrWorkforceAttritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/workforce/succession': {
      id: '/_app/hr/workforce/succession'
      path: '/hr/workforce/succession'
      fullPath: '/hr/workforce/succession'
      preLoaderRoute: typeof AppHrWorkforceSuccessionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppHrEmployeesRouteChildren {
  AppHrEmployeesProfileRoute: typeof AppHrEmployeesProfileRoute
}

const AppHrEmployeesRouteChildren: AppHrEmployeesRouteChildren = {
  AppHrEmployeesProfileRoute: AppHrEmployeesProfileRoute,
}

const AppHrEmployeesRouteWithChildren = AppHrEmployeesRoute._addFileChildren(
  AppHrEmployeesRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsDevicesRoute: typeof AppAssetsDevicesRoute
  AppAttendanceHistoryRoute: typeof AppAttendanceHistoryRoute
  AppAttendanceTodayRoute: typeof AppAttendanceTodayRoute
  AppBenefitsExpensesRoute: typeof AppBenefitsExpensesRoute
  AppCareerGoalsRoute: typeof AppCareerGoalsRoute
  AppHelpdeskTicketsRoute: typeof AppHelpdeskTicketsRoute
  AppHrApprovalsRoute: typeof AppHrApprovalsRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRouteWithChildren
  AppLearningCoursesRoute: typeof AppLearningCoursesRoute
  AppLeaveApplyRoute: typeof AppLeaveApplyRoute
  AppLeaveHistoryRoute: typeof AppLeaveHistoryRoute
  AppLeaveHolidaysRoute: typeof AppLeaveHolidaysRoute
  AppOrgDirectoryRoute: typeof AppOrgDirectoryRoute
  AppPayrollPayslipsRoute: typeof AppPayrollPayslipsRoute
  AppProfilePersonalRoute: typeof AppProfilePersonalRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppLeaveIndexRoute: typeof AppLeaveIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppHrAnalyticsDiversityRoute: typeof AppHrAnalyticsDiversityRoute
  AppHrAnalyticsHeadcountRoute: typeof AppHrAnalyticsHeadcountRoute
  AppHrCompensationBandsRoute: typeof AppHrCompensationBandsRoute
  AppHrCompensationIncrementsRoute: typeof AppHrCompensationIncrementsRoute
  AppHrCompensationPromotionsRoute: typeof AppHrCompensationPromotionsRoute
  AppHrComplianceAuditRoute: typeof AppHrComplianceAuditRoute
  AppHrDocumentsPoliciesRoute: typeof AppHrDocumentsPoliciesRoute
  AppHrEngagementAnnouncementsRoute: typeof AppHrEngagementAnnouncementsRoute
  AppHrEngagementPulseRoute: typeof AppHrEngagementPulseRoute
  AppHrLeaveAdminPoliciesRoute: typeof AppHrLeaveAdminPoliciesRoute
  AppHrLndProgramsRoute: typeof AppHrLndProgramsRoute
  AppHrLndSkillsRoute: typeof AppHrLndSkillsRoute
  AppHrOffboardingResignationsRoute: typeof AppHrOffboardingResignationsRoute
  AppHrOnboardingTasksRoute: typeof AppHrOnboardingTasksRoute
  AppHrOrgDepartmentsRoute: typeof AppHrOrgDepartmentsRoute
  AppHrPerformanceAnalyticsRoute: typeof AppHrPerformanceAnalyticsRoute
  AppHrPerformanceCompetenciesRoute: typeof AppHrPerformanceCompetenciesRoute
  AppHrPerformanceCyclesRoute: typeof AppHrPerformanceCyclesRoute
  AppHrPerformanceEmployeeReviewsRoute: typeof AppHrPerformanceEmployeeReviewsRoute
  AppHrPerformanceGoalsRoute: typeof AppHrPerformanceGoalsRoute
  AppHrRecruitmentAnalyticsRoute: typeof AppHrRecruitmentAnalyticsRoute
  AppHrRecruitmentInterviewsRoute: typeof AppHrRecruitmentInterviewsRoute
  AppHrRecruitmentOffersRoute: typeof AppHrRecruitmentOffersRoute
  AppHrRecruitmentPipelineRoute: typeof AppHrRecruitmentPipelineRoute
  AppHrRecruitmentRequisitionsRoute: typeof AppHrRecruitmentRequisitionsRoute
  AppHrRelationsGrievancesRoute: typeof AppHrRelationsGrievancesRoute
  AppHrWorkforceAttritionRoute: typeof AppHrWorkforceAttritionRoute
  AppHrWorkforceSuccessionRoute: typeof AppHrWorkforceSuccessionRoute
  AppHrAttendanceAdminIndexRoute: typeof AppHrAttendanceAdminIndexRoute
  AppHrComplianceIndexRoute: typeof AppHrComplianceIndexRoute
  AppHrLndIndexRoute: typeof AppHrLndIndexRoute
  AppHrOnboardingIndexRoute: typeof AppHrOnboardingIndexRoute
  AppHrWorkforceIndexRoute: typeof AppHrWorkforceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsDevicesRoute: AppAssetsDevicesRoute,
  AppAttendanceHistoryRoute: AppAttendanceHistoryRoute,
  AppAttendanceTodayRoute: AppAttendanceTodayRoute,
  AppBenefitsExpensesRoute: AppBenefitsExpensesRoute,
  AppCareerGoalsRoute: AppCareerGoalsRoute,
  AppHelpdeskTicketsRoute: AppHelpdeskTicketsRoute,
  AppHrApprovalsRoute: AppHrApprovalsRoute,
  AppHrEmployeesRoute: AppHrEmployeesRouteWithChildren,
  AppLearningCoursesRoute: AppLearningCoursesRoute,
  AppLeaveApplyRoute: AppLeaveApplyRoute,
  AppLeaveHistoryRoute: AppLeaveHistoryRoute,
  AppLeaveHolidaysRoute: AppLeaveHolidaysRoute,
  AppOrgDirectoryRoute: AppOrgDirectoryRoute,
  AppPayrollPayslipsRoute: AppPayrollPayslipsRoute,
  AppProfilePersonalRoute: AppProfilePersonalRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppLeaveIndexRoute: AppLeaveIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppHrAnalyticsDiversityRoute: AppHrAnalyticsDiversityRoute,
  AppHrAnalyticsHeadcountRoute: AppHrAnalyticsHeadcountRoute,
  AppHrCompensationBandsRoute: AppHrCompensationBandsRoute,
  AppHrCompensationIncrementsRoute: AppHrCompensationIncrementsRoute,
  AppHrCompensationPromotionsRoute: AppHrCompensationPromotionsRoute,
  AppHrComplianceAuditRoute: AppHrComplianceAuditRoute,
  AppHrDocumentsPoliciesRoute: AppHrDocumentsPoliciesRoute,
  AppHrEngagementAnnouncementsRoute: AppHrEngagementAnnouncementsRoute,
  AppHrEngagementPulseRoute: AppHrEngagementPulseRoute,
  AppHrLeaveAdminPoliciesRoute: AppHrLeaveAdminPoliciesRoute,
  AppHrLndProgramsRoute: AppHrLndProgramsRoute,
  AppHrLndSkillsRoute: AppHrLndSkillsRoute,
  AppHrOffboardingResignationsRoute: AppHrOffboardingResignationsRoute,
  AppHrOnboardingTasksRoute: AppHrOnboardingTasksRoute,
  AppHrOrgDepartmentsRoute: AppHrOrgDepartmentsRoute,
  AppHrPerformanceAnalyticsRoute: AppHrPerformanceAnalyticsRoute,
  AppHrPerformanceCompetenciesRoute: AppHrPerformanceCompetenciesRoute,
  AppHrPerformanceCyclesRoute: AppHrPerformanceCyclesRoute,
  AppHrPerformanceEmployeeReviewsRoute: AppHrPerformanceEmployeeReviewsRoute,
  AppHrPerformanceGoalsRoute: AppHrPerformanceGoalsRoute,
  AppHrRecruitmentAnalyticsRoute: AppHrRecruitmentAnalyticsRoute,
  AppHrRecruitmentInterviewsRoute: AppHrRecruitmentInterviewsRoute,
  AppHrRecruitmentOffersRoute: AppHrRecruitmentOffersRoute,
  AppHrRecruitmentPipelineRoute: AppHrRecruitmentPipelineRoute,
  AppHrRecruitmentRequisitionsRoute: AppHrRecruitmentRequisitionsRoute,
  AppHrRelationsGrievancesRoute: AppHrRelationsGrievancesRoute,
  AppHrWorkforceAttritionRoute: AppHrWorkforceAttritionRoute,
  AppHrWorkforceSuccessionRoute: AppHrWorkforceSuccessionRoute,
  AppHrAttendanceAdminIndexRoute: AppHrAttendanceAdminIndexRoute,
  AppHrComplianceIndexRoute: AppHrComplianceIndexRoute,
  AppHrLndIndexRoute: AppHrLndIndexRoute,
  AppHrOnboardingIndexRoute: AppHrOnboardingIndexRoute,
  AppHrWorkforceIndexRoute: AppHrWorkforceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
