# Generated by Django 5.1.15 on 2026-08-12 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ess', '0002_employee_organization_employment_band_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('company', 'Company')], default='individual', max_length=12)),
                ('category', models.CharField(choices=[('career', 'Career'), ('team', 'Team'), ('learning', 'Learning'), ('personal', 'Personal')], default='team', max_length=12)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('completed', 'Completed')], default='on_track', max_length=12)),
                ('due', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='ess.employee')),
            ],
            options={
                'ordering': ('due',),
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target', models.CharField(blank=True, max_length=64)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='performance.goal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=96)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('review_window', models.CharField(blank=True, max_length=96)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('self_review', 'Self review'), ('manager_review', 'Manager review'), ('calibration', 'Calibration'), ('closed', 'Closed')], default='upcoming', max_length=20)),
                ('eligible', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('template', models.CharField(blank=True, max_length=96)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-period_start',),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performancecycle'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('reviewer', models.CharField(max_length=128)),
                ('reviewer_title', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('calibrated', 'Calibrated'), ('shared', 'Shared'), ('acknowledged', 'Acknowledged')], default='not_started', max_length=16)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ess.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=128)),
                ('incumbent', models.CharField(max_length=128)),
                ('ready_now', models.JSONField(default=list)),
                ('ready_1yr', models.JSONField(default=list)),
                ('ready_2yr', models.JSONField(default=list)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=96)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('functional', 'Functional'), ('behavioral', 'Behavioral'), ('technical', 'Technical')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('levels', models.PositiveIntegerField(default=5)),
                ('applies', models.JSONField(default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
