# Generated by Django 5.1.15 on 2026-07-26 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditevent',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='target_type',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_c1f818_idx'),
        ),
    ]
